"""Static seed data for Quiz d'Antan.

8 categories (6 thématiques + 2 culture générale par génération) and ~100 questions.
"""

CATEGORIES = [
    {
        "id": "annees-50-60",
        "title": "Années 50-60",
        "description": "Télé, musique, événements et icônes des Trente Glorieuses.",
        "color": "#E07A5F",
        "icon": "tv",
        "mascot_image": "/api/static/mascots/annees-50-60.png",
        "mascot_name": "Robert le Téléspectateur",
        "count": 10,
    },
    {
        "id": "chansons",
        "title": "Chansons",
        "description": "Les grands succès d'Édith Piaf à Brassens, en passant par Trenet.",
        "color": "#722F37",
        "icon": "music",
        "mascot_image": "/api/static/mascots/chansons.png",
        "mascot_name": "Yvette la Chanteuse",
        "count": 10,
    },
    {
        "id": "cinema",
        "title": "Cinéma",
        "description": "Films cultes, acteurs inoubliables et répliques mythiques.",
        "color": "#1E3A5F",
        "icon": "film",
        "mascot_image": "/api/static/mascots/cinema.png",
        "mascot_name": "Marcel le Projectionniste",
        "count": 10,
    },
    {
        "id": "objets-antan",
        "title": "Objets d'antan",
        "description": "Saurez-vous reconnaître les objets d'autrefois ?",
        "color": "#F2CC8F",
        "icon": "phone",
        "mascot_image": "/api/static/mascots/objets-antan.png",
        "mascot_name": "Mémé Suzanne",
        "count": 10,
    },
    {
        "id": "histoire-france",
        "title": "Histoire de France",
        "description": "Événements marquants et grands personnages de notre histoire.",
        "color": "#3D9970",
        "icon": "landmark",
        "mascot_image": "/api/static/mascots/histoire-france.png",
        "mascot_name": "Maître Henri",
        "count": 10,
    },
    {
        "id": "cuisine-terroir",
        "title": "Cuisine & Terroir",
        "description": "Recettes, produits et traditions des régions de France.",
        "color": "#D97706",
        "icon": "utensils",
        "mascot_image": "/api/static/mascots/cuisine-terroir.png",
        "mascot_name": "Chef Bernard",
        "count": 10,
    },
    {
        "id": "culture-40-ans",
        "title": "Génération 40 ans",
        "description": "Pop culture, tech et événements des années 90 et 2000.",
        "color": "#8B5CF6",
        "icon": "sparkles",
        "mascot_image": "/api/static/mascots/culture-40-ans.png",
        "mascot_name": "Sophie la Quadra",
        "count": 20,
    },
    {
        "id": "culture-70-ans",
        "title": "Génération 70 ans",
        "description": "Culture générale des années 60-70 : société, sciences, monde.",
        "color": "#0F766E",
        "icon": "book",
        "mascot_image": "/api/static/mascots/culture-70-ans.png",
        "mascot_name": "Pierre le Sage",
        "count": 20,
    },
]


def _q(qid, cat, question, options, correct, explanation):
    return {
        "id": qid,
        "category_id": cat,
        "question": question,
        "options": options,
        "correct_index": correct,
        "explanation": explanation,
    }


QUESTIONS = [
    # ============================================================
    # Années 50-60 (10 questions)
    # ============================================================
    _q("a1", "annees-50-60",
       "En quelle année la télévision française a-t-elle diffusé son premier journal télévisé ?",
       ["1949", "1954", "1959", "1962"], 0,
       "Le tout premier JT de la télévision française a été diffusé le 29 juin 1949 par la RTF."),
    _q("a2", "annees-50-60",
       "Quel cycliste français a remporté trois Tours de France de suite dans les années 1950 ?",
       ["Jacques Anquetil", "Louison Bobet", "Raymond Poulidor", "Roger Walkowiak"], 1,
       "Louison Bobet a remporté trois Tours de France consécutifs en 1953, 1954 et 1955."),
    _q("a3", "annees-50-60",
       "Comment était surnommée la 2CV Citroën lancée en 1948 ?",
       ["La Coccinelle", "La Deudeuche", "La Quatrelle", "La Traction"], 1,
       "La 2CV était surnommée affectueusement la « Deudeuche ». Elle a été produite jusqu'en 1990."),
    _q("a4", "annees-50-60",
       "Quel programme musical télévisé a été lancé en 1959 ?",
       ["Salut les copains", "Âge tendre et tête de bois", "Discorama", "Le Palmarès des chansons"], 1,
       "« Âge tendre et tête de bois » présenté par Albert Raisner a accompagné la jeunesse yéyé."),
    _q("a5", "annees-50-60",
       "Qui a remporté la Coupe du monde de football en 1958, l'année de la révélation de Pelé ?",
       ["Le Brésil", "La France", "La Suède", "L'Allemagne"], 0,
       "Le Brésil a remporté son premier titre mondial en 1958, en Suède, grâce à un jeune Pelé."),
    _q("a6", "annees-50-60",
       "Quel grand magasin parisien a célébré son centenaire en 1969 ?",
       ["Le Bon Marché", "Les Galeries Lafayette", "La Samaritaine", "Le Printemps"], 1,
       "Les Galeries Lafayette, fondées en 1893, sont devenues incontournables sous la coupole emblématique."),
    _q("a7", "annees-50-60",
       "Quel mouvement de mai 1968 a marqué la France ?",
       ["La grève des mineurs", "Les barricades étudiantes", "La marche des paysans", "La mutinerie"], 1,
       "Mai 68 fut un vaste mouvement social initié par les étudiants au quartier latin de Paris."),
    _q("a8", "annees-50-60",
       "Comment s'appelait le premier satellite français lancé en 1965 ?",
       ["Spoutnik", "Astérix", "Diamant", "Mercure"], 1,
       "Astérix, premier satellite français, a été placé en orbite le 26 novembre 1965 par la fusée Diamant."),
    _q("a9", "annees-50-60",
       "Quel acteur populaire est mort en 1971 et fut un grand comique du music-hall ?",
       ["Bourvil", "Fernandel", "Louis de Funès", "Pierre Brasseur"], 0,
       "Bourvil, immense acteur et chanteur populaire, est décédé le 23 septembre 1970."),
    _q("a10", "annees-50-60",
       "Quel chanteur s'est imposé avec « Souvenirs, souvenirs » en 1958 ?",
       ["Eddy Mitchell", "Johnny Hallyday", "Claude François", "Sacha Distel"], 1,
       "Johnny Hallyday a fait ses débuts avec cette chanson rock'n'roll en 1958, qui a lancé sa carrière."),

    # ============================================================
    # Chansons (10 questions)
    # ============================================================
    _q("c1", "chansons",
       "Quel chanteur français a composé et interprété « La Mer » en 1946 ?",
       ["Édith Piaf", "Charles Trenet", "Jacques Brel", "Georges Brassens"], 1,
       "Charles Trenet a composé « La Mer » en 1943 et l'a enregistrée en 1946."),
    _q("c2", "chansons",
       "Qui a interprété « La Vie en rose » en 1945 ?",
       ["Mireille Mathieu", "Édith Piaf", "Dalida", "Juliette Gréco"], 1,
       "Édith Piaf a écrit les paroles de « La Vie en rose » en 1945, son plus grand succès international."),
    _q("c3", "chansons",
       "« Ne me quitte pas » est une chanson emblématique de quel artiste ?",
       ["Léo Ferré", "Jacques Brel", "Serge Gainsbourg", "Aznavour"], 1,
       "Jacques Brel a composé cette chanson en 1959. Elle reste l'une des plus reprises."),
    _q("c4", "chansons",
       "Qui chantait « Les Champs-Élysées » en 1969 ?",
       ["Sacha Distel", "Joe Dassin", "Claude François", "Hugues Aufray"], 1,
       "Joe Dassin a fait de cette chanson un hit international."),
    _q("c5", "chansons",
       "Quel chanteur est l'auteur de « La Bohème » en 1965 ?",
       ["Charles Aznavour", "Yves Montand", "Gilbert Bécaud", "Serge Reggiani"], 0,
       "Charles Aznavour a écrit « La Bohème » avec Jacques Plante, évoquant Montmartre artiste."),
    _q("c6", "chansons",
       "Qui a popularisé « Les copains d'abord » en 1964 ?",
       ["Georges Brassens", "Léo Ferré", "Hugues Aufray", "Jacques Brel"], 0,
       "Georges Brassens, poète et chanteur, a écrit ce titre pour un film de Yves Robert."),
    _q("c7", "chansons",
       "Quelle chanteuse a été surnommée « la môme » avant ses débuts ?",
       ["Mireille Mathieu", "Édith Piaf", "Dalida", "Barbara"], 1,
       "Édith Piaf, découverte chantant dans la rue, fut d'abord surnommée « la môme Piaf »."),
    _q("c8", "chansons",
       "Quel artiste a chanté « Comme d'habitude » en 1967, repris par Sinatra ?",
       ["Joe Dassin", "Claude François", "Michel Sardou", "Eddy Mitchell"], 1,
       "Claude François a coécrit ce titre devenu « My Way » dans la version anglaise de Sinatra."),
    _q("c9", "chansons",
       "Qui interprète « Capri c'est fini » en 1965 ?",
       ["Hervé Vilard", "Adamo", "Antoine", "Christophe"], 0,
       "Hervé Vilard a connu un succès retentissant avec cette chanson écrite à 19 ans."),
    _q("c10", "chansons",
       "Quelle chanson de Dalida est sortie en 1973 et reste un classique ?",
       ["Bambino", "Gigi l'Amoroso", "Paroles, paroles", "Mourir sur scène"], 2,
       "« Paroles, paroles » en duo avec Alain Delon est devenu un classique français."),

    # ============================================================
    # Cinéma (10 questions)
    # ============================================================
    _q("ci1", "cinema",
       "Dans quel film de 1956 Brigitte Bardot devient une icône mondiale ?",
       ["Et Dieu… créa la femme", "En cas de malheur", "La Vérité", "Le Mépris"], 0,
       "« Et Dieu… créa la femme » de Roger Vadim a fait de Bardot un mythe du cinéma."),
    _q("ci2", "cinema",
       "Qui est le réalisateur du film « Les Tontons flingueurs » (1963) ?",
       ["Henri Verneuil", "Georges Lautner", "Claude Sautet", "Gérard Oury"], 1,
       "Georges Lautner a réalisé ce film culte avec les dialogues de Michel Audiard."),
    _q("ci3", "cinema",
       "Quel duo d'acteurs joue dans « La Grande Vadrouille » (1966) ?",
       ["Bourvil et De Funès", "Belmondo et Delon", "Gabin et Fernandel", "Ventura et Belmondo"], 0,
       "Louis de Funès et Bourvil forment le duo inoubliable de ce film de Gérard Oury."),
    _q("ci4", "cinema",
       "Dans quel film Jean Gabin traverse Paris avec une cargaison de viande clandestine ?",
       ["La Traversée de Paris", "Le Cave se rebiffe", "Le Pacha", "Archimède le clochard"], 0,
       "« La Traversée de Paris » de Claude Autant-Lara (1956) avec Bourvil et Gabin."),
    _q("ci5", "cinema",
       "Qui réalise « À bout de souffle » en 1960, manifeste de la Nouvelle Vague ?",
       ["François Truffaut", "Jean-Luc Godard", "Claude Chabrol", "Éric Rohmer"], 1,
       "Jean-Luc Godard a révolutionné le cinéma avec ce film avec Belmondo et Seberg."),
    _q("ci6", "cinema",
       "Quel acteur français a remporté un Oscar pour « Le Dernier Métro » en 1980 ?",
       ["Gérard Depardieu", "Catherine Deneuve", "Philippe Noiret", "Aucun"], 3,
       "Le film de Truffaut a reçu 10 Césars en 1981 mais pas l'Oscar du meilleur acteur."),
    _q("ci7", "cinema",
       "Quel film de Jean-Paul Rappeneau a triomphé en 1990 avec Depardieu ?",
       ["Cyrano de Bergerac", "Le Hussard sur le toit", "Bon voyage", "Tous les matins du monde"], 0,
       "« Cyrano de Bergerac » a remporté 10 Césars et reste un sommet du cinéma français."),
    _q("ci8", "cinema",
       "Qui réalise « Le Fabuleux Destin d'Amélie Poulain » en 2001 ?",
       ["Luc Besson", "Jean-Pierre Jeunet", "Mathieu Kassovitz", "Claude Berri"], 1,
       "Jean-Pierre Jeunet a offert à Audrey Tautou le rôle qui l'a rendue célèbre."),
    _q("ci9", "cinema",
       "Dans quel film Coluche reçoit-il le César du meilleur acteur en 1984 ?",
       ["Tchao Pantin", "L'Aile ou la Cuisse", "Banzaï", "Inspecteur la Bavure"], 0,
       "Claude Berri lui offre un rôle dramatique dans « Tchao Pantin » qui révèle son talent."),
    _q("ci10", "cinema",
       "Qui réalise « La Vie est belle » (La vita è bella) en 1997 ?",
       ["Roberto Benigni", "Federico Fellini", "Giuseppe Tornatore", "Bernardo Bertolucci"], 0,
       "Roberto Benigni a réalisé et joué dans ce film oscarisé sur la Shoah."),

    # ============================================================
    # Objets d'antan (10 questions)
    # ============================================================
    _q("o1", "objets-antan",
       "Comment appelle-t-on l'appareil servant à écouter les disques vinyles ?",
       ["Un magnétoscope", "Un électrophone", "Un gramophone", "Un transistor"], 1,
       "L'électrophone était l'appareil utilisé pour écouter les vinyles dans les années 50 à 80."),
    _q("o2", "objets-antan",
       "Quel objet servait à filer la laine à la maison ?",
       ["Un rouet", "Un métier à tisser", "Une quenouille", "Un dévidoir"], 0,
       "Le rouet était présent dans de nombreuses maisons rurales pour filer la laine."),
    _q("o3", "objets-antan",
       "Qu'est-ce qu'une « TSF » ?",
       ["Un téléphone à cadran", "Une radio sans fil", "Un télégraphe", "Une machine à écrire"], 1,
       "TSF signifie « Télégraphie sans fil » : les postes de radio du début du XXᵉ siècle."),
    _q("o4", "objets-antan",
       "Quel ustensile servait à allumer le feu dans la cheminée ?",
       ["Un soufflet", "Un tisonnier", "Une braise", "Une chaufferette"], 0,
       "Le soufflet permettait d'envoyer de l'air sur les braises pour raviver le feu."),
    _q("o5", "objets-antan",
       "Qu'utilisait-on pour conserver le lait au frais avant le réfrigérateur ?",
       ["Une glacière à blocs de glace", "Un coffre en bois", "Une jarre en terre", "Tout cela"], 3,
       "On utilisait des glacières à blocs, des jarres et la fraîcheur des caves pour conserver."),
    _q("o6", "objets-antan",
       "Comment s'appelle le récipient pour transporter le lait à la ferme ?",
       ["Un broc", "Un bidon", "Une bouteille", "Une jarre"], 1,
       "Le bidon métallique, parfois sur un porteur, était l'outil quotidien du laitier."),
    _q("o7", "objets-antan",
       "Quel objet ornait la cheminée et indiquait le temps avec une figurine ?",
       ["Un baromètre", "Une pendule", "Un thermomètre", "Une girouette"], 0,
       "Le baromètre, souvent décoré, indiquait la pression atmosphérique et donc le beau temps."),
    _q("o8", "objets-antan",
       "Comment appelle-t-on l'appareil à manivelle pour repasser le linge ?",
       ["Un fer à charbon", "Une calandre", "Une essoreuse", "Un repassoir"], 1,
       "La calandre, à manivelle, lissait les draps entre deux rouleaux chauffés."),
    _q("o9", "objets-antan",
       "Quel objet en bois servait à laver le linge au lavoir ?",
       ["Un battoir", "Un manche à balai", "Une planche", "Une louche"], 0,
       "Le battoir, en bois dur, servait à frapper le linge pour en faire sortir la saleté."),
    _q("o10", "objets-antan",
       "Quel objet sonore réveillait les villages avant les horloges électriques ?",
       ["Le clairon", "La cloche de l'église", "Le tambour", "La corne"], 1,
       "Les cloches de l'église rythmaient la journée : angélus, messes et heures."),

    # ============================================================
    # Histoire de France (10 questions)
    # ============================================================
    _q("h1", "histoire-france",
       "En quelle année a eu lieu la prise de la Bastille ?",
       ["1788", "1789", "1791", "1793"], 1,
       "Le 14 juillet 1789, le peuple parisien prit la Bastille, événement fondateur de la Révolution."),
    _q("h2", "histoire-france",
       "Qui était président de la République lors de l'appel du 18 juin 1940 ?",
       ["Albert Lebrun", "Paul Reynaud", "Édouard Daladier", "Philippe Pétain"], 0,
       "Albert Lebrun fut le dernier président de la IIIᵉ République."),
    _q("h3", "histoire-france",
       "Sous quel roi a été construit le château de Versailles ?",
       ["Louis XIII", "Louis XIV", "Louis XV", "Louis XVI"], 1,
       "Louis XIV a fait agrandir le pavillon de chasse de son père pour en faire le palais royal en 1682."),
    _q("h4", "histoire-france",
       "En quelle année Charles de Gaulle est-il devenu président de la Vᵉ République ?",
       ["1945", "1958", "1962", "1969"], 1,
       "De Gaulle est élu président par un collège électoral le 21 décembre 1958."),
    _q("h5", "histoire-france",
       "Qui a couronné Napoléon Bonaparte empereur en 1804 ?",
       ["Le pape Pie VII", "Lui-même", "Joséphine", "Talleyrand"], 1,
       "Napoléon se couronne lui-même en présence du pape Pie VII à Notre-Dame de Paris."),
    _q("h6", "histoire-france",
       "Quelle bataille marque la fin de Napoléon en 1815 ?",
       ["Austerlitz", "Iéna", "Waterloo", "Trafalgar"], 2,
       "La défaite à Waterloo (Belgique) face aux Anglo-Prussiens scelle son destin."),
    _q("h7", "histoire-france",
       "Qui était Jeanne d'Arc ?",
       ["Une princesse", "Une bergère devenue chef de guerre", "Une reine", "Une mère supérieure"], 1,
       "Jeanne d'Arc, jeune bergère lorraine, mena les armées françaises sous Charles VII."),
    _q("h8", "histoire-france",
       "En quelle année la France a-t-elle aboli l'esclavage définitivement ?",
       ["1789", "1815", "1848", "1865"], 2,
       "Victor Schœlcher fit voter le décret d'abolition de l'esclavage le 27 avril 1848."),
    _q("h9", "histoire-france",
       "Quel président français a instauré les congés payés en 1936 ?",
       ["Léon Blum", "Édouard Daladier", "Albert Lebrun", "Paul Reynaud"], 0,
       "Léon Blum, président du Conseil du Front populaire, accorde 15 jours de congés payés."),
    _q("h10", "histoire-france",
       "Qui était le « roi-soleil » ?",
       ["Louis XIII", "Louis XIV", "Louis XV", "Henri IV"], 1,
       "Louis XIV, surnommé le Roi-Soleil, a régné 72 ans (1643-1715)."),

    # ============================================================
    # Cuisine & Terroir (10 questions)
    # ============================================================
    _q("cu1", "cuisine-terroir",
       "Quelle est la spécialité culinaire emblématique de la Provence ?",
       ["La bouillabaisse", "Le cassoulet", "La tartiflette", "Le pot-au-feu"], 0,
       "La bouillabaisse est la soupe de poissons emblématique de Marseille."),
    _q("cu2", "cuisine-terroir",
       "Avec quel fromage prépare-t-on traditionnellement la tartiflette ?",
       ["Le beaufort", "Le reblochon", "L'emmental", "Le comté"], 1,
       "La tartiflette savoyarde se prépare avec du reblochon, pommes de terre, oignons et lardons."),
    _q("cu3", "cuisine-terroir",
       "Quelle ville est célèbre pour ses canelés ?",
       ["Bordeaux", "Toulouse", "Nantes", "Lyon"], 0,
       "Le canelé est une spécialité bordelaise à base de rhum et de vanille."),
    _q("cu4", "cuisine-terroir",
       "Le kouign-amann est une pâtisserie traditionnelle de quelle région ?",
       ["Normandie", "Bretagne", "Alsace", "Pays Basque"], 1,
       "Le kouign-amann (« gâteau au beurre » en breton) est né à Douarnenez vers 1860."),
    _q("cu5", "cuisine-terroir",
       "De quelle ville le cassoulet est-il une spécialité reconnue ?",
       ["Toulouse", "Castelnaudary", "Carcassonne", "Toutes ces villes"], 3,
       "Toulouse, Castelnaudary et Carcassonne se disputent la paternité du cassoulet."),
    _q("cu6", "cuisine-terroir",
       "Quel vin sucré accompagne traditionnellement le foie gras ?",
       ["Le Bordeaux", "Le Sauternes", "Le Champagne", "Le Beaujolais"], 1,
       "Le Sauternes, vin liquoreux, est l'accord classique avec le foie gras."),
    _q("cu7", "cuisine-terroir",
       "Quelle est l'origine du fromage Roquefort ?",
       ["Aveyron", "Lozère", "Cantal", "Lot"], 0,
       "Le Roquefort, fromage de brebis à pâte persillée, est affiné dans les caves de Roquefort-sur-Soulzon (Aveyron)."),
    _q("cu8", "cuisine-terroir",
       "Quel plat lyonnais est composé de panse de veau panée et grillée ?",
       ["La rosette", "Le tablier de sapeur", "La salade lyonnaise", "Les pommes lyonnaises"], 1,
       "Le tablier de sapeur est une spécialité lyonnaise de gras-double pané et frit, accompagné de sauce gribiche."),
    _q("cu9", "cuisine-terroir",
       "Quel est l'ingrédient principal de la ratatouille niçoise ?",
       ["Le chou", "L'aubergine", "La courgette", "La tomate"], 1,
       "L'aubergine est centrale, mais la ratatouille marie aubergine, courgette, tomate et poivron."),
    _q("cu10", "cuisine-terroir",
       "Quelle pâtisserie alsacienne a la forme d'une étoile en chocolat ?",
       ["Le bredele", "Le kougelhopf", "L'amandine", "Le mannele"], 0,
       "Les bredele sont des petits biscuits alsaciens variés préparés à Noël."),

    # ============================================================
    # Génération 40 ans — Culture 90s & 2000s (20 questions)
    # ============================================================
    _q("q40_1", "culture-40-ans",
       "Quel dessin animé culte de TF1 mettait en scène Goldorak dans les années 80 ?",
       ["Albator", "Goldorak", "Capitaine Flam", "Cobra"], 1,
       "Goldorak, diffusé en 1978 sur Antenne 2, est devenu un phénomène pour la génération des quadras."),
    _q("q40_2", "culture-40-ans",
       "En quelle année l'euro est-il devenu la monnaie quotidienne en France ?",
       ["1999", "2000", "2002", "2004"], 2,
       "Les pièces et billets en euros ont remplacé le franc le 1ᵉʳ janvier 2002."),
    _q("q40_3", "culture-40-ans",
       "Quel groupe français a marqué les années 80-90 avec « L'Aventurier » ?",
       ["Indochine", "Téléphone", "Les Innocents", "Cookie Dingler"], 0,
       "Indochine, formé en 1981, est devenu le groupe culte d'une génération avec « L'Aventurier » (1982) et « Trois nuits par semaine »."),
    _q("q40_4", "culture-40-ans",
       "Quel est le premier téléphone portable Nokia à devenir un phénomène mondial ?",
       ["Nokia 3210", "Nokia 3310", "Nokia 8210", "Nokia 6610"], 1,
       "Le Nokia 3310, sorti en 2000, s'est vendu à plus de 126 millions d'exemplaires."),
    _q("q40_5", "culture-40-ans",
       "Quel film français de 1996 a révélé Mathieu Kassovitz comme réalisateur ?",
       ["La Haine", "Métisse", "Les Rivières pourpres", "Assassin(s)"], 0,
       "« La Haine » (1995) raconte une journée en banlieue avec Vincent Cassel."),
    _q("q40_6", "culture-40-ans",
       "Quelle équipe a remporté la Coupe du monde de football en 1998 ?",
       ["Le Brésil", "La France", "L'Italie", "L'Allemagne"], 1,
       "La France a remporté son premier titre mondial au Stade de France contre le Brésil (3-0)."),
    _q("q40_7", "culture-40-ans",
       "Qui est l'auteur de la saga « Harry Potter » ?",
       ["Stephen King", "J.K. Rowling", "Roald Dahl", "Philip Pullman"], 1,
       "J.K. Rowling a publié le premier tome en 1997, traduit en français en 1998."),
    _q("q40_8", "culture-40-ans",
       "Quel groupe de pop français a chanté « Les Démons de minuit » en 1986 ?",
       ["Émile et Images", "Niagara", "Indochine", "Téléphone"], 0,
       "Émile et Images a marqué la pop française avec ce tube en 1986."),
    _q("q40_9", "culture-40-ans",
       "En quelle année Internet est-il devenu grand public en France ?",
       ["1990", "1995", "2000", "2005"], 1,
       "Internet s'est démocratisé en France à partir de 1995 avec l'arrivée des premiers fournisseurs grand public."),
    _q("q40_10", "culture-40-ans",
       "Quel jeu vidéo Nintendo culte est sorti en 1996 sur Nintendo 64 ?",
       ["Super Mario 64", "Zelda Ocarina of Time", "Mario Kart", "Donkey Kong 64"], 0,
       "« Super Mario 64 » a révolutionné les jeux de plateforme en 3D."),
    _q("q40_11", "culture-40-ans",
       "Quel film de Disney a marqué l'année 1994 avec son ouverture mythique en Afrique ?",
       ["Le Roi Lion", "Aladdin", "Pocahontas", "Tarzan"], 0,
       "« Le Roi Lion » (1994) reste l'un des plus grands succès de l'animation Disney."),
    _q("q40_12", "culture-40-ans",
       "Qui chante « Allumer le feu » à l'aube de l'an 2000 au Stade de France ?",
       ["Johnny Hallyday", "Patrick Bruel", "Michel Sardou", "Pascal Obispo"], 0,
       "Johnny Hallyday a donné un concert mémorable au Stade de France à minuit le 31 décembre 1999."),
    _q("q40_13", "culture-40-ans",
       "Quel film de Luc Besson met en scène Natalie Portman en 1994 ?",
       ["Léon", "Le Cinquième Élément", "Nikita", "Subway"], 0,
       "« Léon » (1994) avec Jean Reno a révélé Natalie Portman à 12 ans."),
    _q("q40_14", "culture-40-ans",
       "Quel président français a démissionné en 1995 pour laisser place à Chirac ?",
       ["Valéry Giscard d'Estaing", "François Mitterrand", "Lionel Jospin", "Aucun, terminé son mandat"], 3,
       "Mitterrand a terminé ses deux mandats (1981-1995). Chirac lui a succédé après élection."),
    _q("q40_15", "culture-40-ans",
       "Quel jeu de société des années 80 utilise des questions colorées de culture générale ?",
       ["Monopoly", "Trivial Pursuit", "Cluedo", "Risk"], 1,
       "Le Trivial Pursuit, créé en 1981, est devenu le jeu de culture générale par excellence."),
    _q("q40_16", "culture-40-ans",
       "Quelle série française des années 90 suivait trois amies à Saint-Tropez ?",
       ["Hélène et les Garçons", "Premiers Baisers", "Sous le Soleil", "Salut les Musclés"], 2,
       "« Sous le Soleil » (1996-2008), diffusée sur TF1, suivait trois amies — Laure, Caroline et Jessica — à Saint-Tropez."),
    _q("q40_17", "culture-40-ans",
       "Quel téléphone d'Apple a lancé la révolution smartphone en 2007 ?",
       ["iPod Touch", "iPhone", "iPad", "MacBook"], 1,
       "L'iPhone, présenté par Steve Jobs le 9 janvier 2007, a transformé la téléphonie."),
    _q("q40_18", "culture-40-ans",
       "Quel groupe de R&B français a percé en 1996 avec « Be My Lady » ?",
       ["Alliage", "G-Squad", "2 Be 3", "Worlds Apart"], 0,
       "Alliage, boys band français, a connu un succès fulgurant avec ce titre."),
    _q("q40_19", "culture-40-ans",
       "Quel jeu télévisé a été lancé par Jean-Pierre Foucault en 2000 ?",
       ["Le Juste Prix", "Qui veut gagner des millions ?", "La Roue de la fortune", "Tournez Manège"], 1,
       "« Qui veut gagner des millions ? » sur TF1 a battu des records d'audience."),
    _q("q40_20", "culture-40-ans",
       "Quel film français de 2008 réalisé par Dany Boon est un immense succès ?",
       ["Bienvenue chez les Ch'tis", "Rien à déclarer", "La Maison du Bonheur", "Eyjafjallajökull"], 0,
       "« Bienvenue chez les Ch'tis » a attiré plus de 20 millions de spectateurs en France."),

    # ============================================================
    # Génération 70 ans — Culture 60s-70s (20 questions)
    # ============================================================
    _q("q70_1", "culture-70-ans",
       "En quelle année Neil Armstrong a-t-il marché sur la Lune ?",
       ["1965", "1969", "1972", "1975"], 1,
       "Le 21 juillet 1969, Neil Armstrong est devenu le premier homme à fouler le sol lunaire."),
    _q("q70_2", "culture-70-ans",
       "Quel président américain a été assassiné à Dallas en 1963 ?",
       ["Lyndon Johnson", "John F. Kennedy", "Richard Nixon", "Eisenhower"], 1,
       "John F. Kennedy a été assassiné le 22 novembre 1963 à Dallas, Texas."),
    _q("q70_3", "culture-70-ans",
       "Quel mur a divisé une ville européenne de 1961 à 1989 ?",
       ["Le Mur de Berlin", "Le Mur de Paris", "Le Mur d'Athènes", "Le Mur de Vienne"], 0,
       "Le Mur de Berlin séparait Berlin-Est et Berlin-Ouest jusqu'à sa chute le 9 novembre 1989."),
    _q("q70_4", "culture-70-ans",
       "Quel groupe britannique a marqué les années 60 avec « Yesterday » ?",
       ["The Rolling Stones", "The Beatles", "Pink Floyd", "The Who"], 1,
       "« Yesterday » des Beatles (1965), composée par Paul McCartney, est l'une des chansons les plus reprises."),
    _q("q70_5", "culture-70-ans",
       "Qui a dirigé l'URSS pendant la crise des missiles de Cuba en 1962 ?",
       ["Staline", "Khrouchtchev", "Brejnev", "Gorbatchev"], 1,
       "Nikita Khrouchtchev a négocié avec Kennedy lors de cette crise majeure de la guerre froide."),
    _q("q70_6", "culture-70-ans",
       "Quelle découverte scientifique majeure a été faite en 1953 par Watson et Crick ?",
       ["La pénicilline", "La structure de l'ADN", "La radioactivité", "Le vaccin contre la polio"], 1,
       "James Watson et Francis Crick ont décrit la double hélice de l'ADN, révolutionnant la biologie."),
    _q("q70_7", "culture-70-ans",
       "Quel pays a accueilli les Jeux olympiques d'été en 1968 ?",
       ["Le Japon", "Le Mexique", "L'Allemagne", "Le Canada"], 1,
       "Mexico 1968 fut marqué par le salut des athlètes afro-américains et l'altitude."),
    _q("q70_8", "culture-70-ans",
       "Quel mouvement pacifiste a marqué les années 60 aux États-Unis ?",
       ["Le hippie", "Le punk", "Le grunge", "Le rock"], 0,
       "Le mouvement hippie, opposé à la guerre du Vietnam, a marqué la contre-culture des années 60."),
    _q("q70_9", "culture-70-ans",
       "Quel livre de Simone de Beauvoir, publié en 1949, est devenu un classique du féminisme ?",
       ["Le Deuxième Sexe", "L'Invitée", "Les Mandarins", "Les Belles Images"], 0,
       "« Le Deuxième Sexe » est une œuvre fondatrice du féminisme moderne."),
    _q("q70_10", "culture-70-ans",
       "Quel premier vol commercial supersonique a relié Paris à New York en 1976 ?",
       ["Le Boeing 747", "Le Concorde", "L'Airbus A300", "Le Tupolev Tu-144"], 1,
       "Le Concorde, fruit de la coopération franco-britannique, a volé jusqu'en 2003."),
    _q("q70_11", "culture-70-ans",
       "Qui a remporté le Tour de France 5 fois entre 1969 et 1974 ?",
       ["Bernard Hinault", "Eddy Merckx", "Jacques Anquetil", "Miguel Indurain"], 1,
       "Le Belge Eddy Merckx, « le Cannibale », est considéré comme l'un des plus grands cyclistes."),
    _q("q70_12", "culture-70-ans",
       "Quel philosophe français a publié « L'Être et le Néant » en 1943 ?",
       ["Albert Camus", "Jean-Paul Sartre", "Maurice Merleau-Ponty", "Raymond Aron"], 1,
       "Jean-Paul Sartre, philosophe existentialiste, a marqué la pensée française du XXᵉ siècle."),
    _q("q70_13", "culture-70-ans",
       "Quelle invention de 1947 a révolutionné l'électronique ?",
       ["Le transistor", "Le tube cathodique", "Le micro-processeur", "Le laser"], 0,
       "Le transistor, inventé aux Bell Labs en 1947, a permis la miniaturisation de l'électronique."),
    _q("q70_14", "culture-70-ans",
       "Quel président français a aboli la peine de mort en 1981 ?",
       ["Valéry Giscard d'Estaing", "François Mitterrand", "Georges Pompidou", "Jacques Chirac"], 1,
       "Le 9 octobre 1981, la loi portée par Robert Badinter sous Mitterrand a aboli la guillotine."),
    _q("q70_15", "culture-70-ans",
       "Quel boxeur surnommé « The Greatest » a refusé de partir au Vietnam ?",
       ["Joe Frazier", "Muhammad Ali", "George Foreman", "Sugar Ray Robinson"], 1,
       "Muhammad Ali a refusé l'incorporation en 1967, lui coûtant son titre pendant 3 ans."),
    _q("q70_16", "culture-70-ans",
       "Quelle ville française a été le siège de l'Exposition universelle de 1937 ?",
       ["Lyon", "Marseille", "Paris", "Lille"], 2,
       "L'Exposition de 1937 à Paris a vu s'affronter symboliquement les pavillons soviétique et nazi."),
    _q("q70_17", "culture-70-ans",
       "Qui a peint « Guernica » en 1937 pour dénoncer la guerre d'Espagne ?",
       ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Marc Chagall"], 1,
       "Pablo Picasso a peint cette œuvre monumentale après le bombardement de Guernica."),
    _q("q70_18", "culture-70-ans",
       "Quel président américain a démissionné suite au scandale du Watergate en 1974 ?",
       ["Lyndon Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter"], 1,
       "Richard Nixon a démissionné le 9 août 1974, seul président américain à l'avoir fait."),
    _q("q70_19", "culture-70-ans",
       "Quel chef d'État chinois a lancé la Révolution culturelle en 1966 ?",
       ["Sun Yat-sen", "Mao Zedong", "Deng Xiaoping", "Tchang Kaï-chek"], 1,
       "Mao Zedong a lancé ce mouvement qui a profondément bouleversé la Chine pendant 10 ans."),
    _q("q70_20", "culture-70-ans",
       "En quelle année Charles de Gaulle a-t-il prononcé son discours de Phnom Penh ?",
       ["1962", "1966", "1968", "1970"], 1,
       "Le 1ᵉʳ septembre 1966, de Gaulle a condamné l'intervention américaine au Vietnam."),
]
