"""Static seed data for Quiz d'Antan."""

CATEGORIES = [
    {
        "id": "annees-50-60",
        "title": "Années 50-60",
        "description": "Télé, musique, événements et icônes des Trente Glorieuses.",
        "color": "#E07A5F",
        "icon": "tv",
        "mascot_image": "/api/static/mascots/annees-50-60.png",
        "mascot_name": "Robert le Téléspectateur",
        "count": 48,
    },
    {
        "id": "chansons",
        "title": "Chansons",
        "description": "Les grands succès d'Édith Piaf à Brassens, en passant par Trenet.",
        "color": "#722F37",
        "icon": "music",
        "mascot_image": "/api/static/mascots/chansons.png",
        "mascot_name": "Yvette la Chanteuse",
        "count": 62,
    },
    {
        "id": "cinema",
        "title": "Cinéma",
        "description": "Films cultes, acteurs inoubliables et répliques mythiques.",
        "color": "#1E3A5F",
        "icon": "film",
        "mascot_image": "/api/static/mascots/cinema.png",
        "mascot_name": "Marcel le Projectionniste",
        "count": 55,
    },
    {
        "id": "objets-antan",
        "title": "Objets d'antan",
        "description": "Saurez-vous reconnaître les objets d'autrefois ?",
        "color": "#F2CC8F",
        "icon": "phone",
        "mascot_image": "/api/static/mascots/objets-antan.png",
        "mascot_name": "Mémé Suzanne",
        "count": 40,
    },
    {
        "id": "histoire-france",
        "title": "Histoire de France",
        "description": "Événements marquants et grands personnages de notre histoire.",
        "color": "#3D9970",
        "icon": "landmark",
        "mascot_image": "/api/static/mascots/histoire-france.png",
        "mascot_name": "Maître Henri",
        "count": 73,
    },
    {
        "id": "cuisine-terroir",
        "title": "Cuisine & Terroir",
        "description": "Recettes, produits et traditions des régions de France.",
        "color": "#D97706",
        "icon": "utensils",
        "mascot_image": "/api/static/mascots/cuisine-terroir.png",
        "mascot_name": "Chef Bernard",
        "count": 38,
    },
]


def _q(qid, cat, question, options, correct, explanation):
    return {
        "id": qid,
        "category_id": cat,
        "question": question,
        "options": options,
        "correct_index": correct,
        "explanation": explanation,
    }


QUESTIONS = [
    # Années 50-60
    _q("a1", "annees-50-60",
       "En quelle année la télévision française a-t-elle diffusé son premier journal télévisé ?",
       ["1949", "1954", "1959", "1962"], 0,
       "Le tout premier JT de la télévision française a été diffusé le 29 juin 1949 par la RTF."),
    _q("a2", "annees-50-60",
       "Quel événement sportif a marqué les Français en 1958 ?",
       ["La victoire au Mondial", "Le Tour de France de Bobet", "Une médaille olympique de Mimoun", "Un match France-Angleterre"], 1,
       "Louison Bobet a marqué cette décennie en remportant trois Tours de France consécutifs (1953, 1954, 1955)."),
    _q("a3", "annees-50-60",
       "Comment s'appelait la célèbre 2CV Citroën lancée en 1948 ?",
       ["La Coccinelle", "La Deudeuche", "La Quatrelle", "La Traction"], 1,
       "La 2CV était surnommée affectueusement la « Deudeuche » par les Français. Elle a été produite jusqu'en 1990."),
    _q("a4", "annees-50-60",
       "Quel programme de variétés a été lancé en 1959 à la télévision ?",
       ["Salut les copains", "Âge tendre et tête de bois", "Discorama", "Le Palmarès des chansons"], 1,
       "« Âge tendre et tête de bois » présenté par Albert Raisner a accompagné la jeunesse yéyé des années 60."),

    # Chansons
    _q("c1", "chansons",
       "Quel chanteur français a composé et interprété « La Mer » en 1946 ?",
       ["Édith Piaf", "Charles Trenet", "Jacques Brel", "Georges Brassens"], 1,
       "Charles Trenet a composé « La Mer » en 1943 et l'a enregistrée en 1946. C'est l'une des chansons françaises les plus connues au monde."),
    _q("c2", "chansons",
       "Qui a interprété « La Vie en rose » en 1945 ?",
       ["Mireille Mathieu", "Édith Piaf", "Dalida", "Juliette Gréco"], 1,
       "Édith Piaf a écrit les paroles de « La Vie en rose » en 1945, devenant son plus grand succès international."),
    _q("c3", "chansons",
       "« Ne me quitte pas » est une chanson emblématique de quel artiste ?",
       ["Léo Ferré", "Jacques Brel", "Serge Gainsbourg", "Aznavour"], 1,
       "Jacques Brel a composé cette chanson en 1959. Elle reste l'une des plus reprises de la chanson française."),
    _q("c4", "chansons",
       "Qui chantait « Les Champs-Élysées » en 1969 ?",
       ["Sacha Distel", "Joe Dassin", "Claude François", "Hugues Aufray"], 1,
       "Joe Dassin a fait de cette chanson un hit international, encore chantée par des générations entières."),

    # Cinéma
    _q("ci1", "cinema",
       "Dans quel film de 1956 Brigitte Bardot portait-elle sa célèbre robe vichy rose ?",
       ["Et Dieu… créa la femme", "En cas de malheur", "La Vérité", "Le Mépris"], 0,
       "Dans « Et Dieu… créa la femme » de Roger Vadim, Brigitte Bardot a créé une icône absolue de mode et de cinéma."),
    _q("ci2", "cinema",
       "Qui est le réalisateur du film « Les Tontons flingueurs » (1963) ?",
       ["Henri Verneuil", "Georges Lautner", "Claude Sautet", "Gérard Oury"], 1,
       "Georges Lautner a réalisé ce film culte, avec les dialogues savoureux de Michel Audiard."),
    _q("ci3", "cinema",
       "Quel acteur tenait le rôle principal de « La Grande Vadrouille » (1966) ?",
       ["Bourvil et De Funès", "Fernandel", "Belmondo", "Pierre Richard"], 0,
       "Louis de Funès et Bourvil forment le duo inoubliable de ce film de Gérard Oury, longtemps record du box-office français."),
    _q("ci4", "cinema",
       "Dans quel film Jean Gabin joue-t-il un cuisinier nommé Antoine Delafoy ?",
       ["La Traversée de Paris", "Le Cave se rebiffe", "Le Pacha", "Archimède le clochard"], 0,
       "« La Traversée de Paris » de Claude Autant-Lara (1956) où Gabin incarne un personnage haut en couleur."),

    # Objets d'antan
    _q("o1", "objets-antan",
       "Comment appelle-t-on l'appareil servant à écouter les disques vinyles ?",
       ["Un magnétoscope", "Un électrophone", "Un gramophone", "Un transistor"], 1,
       "L'électrophone (ou tourne-disque) était l'appareil utilisé pour écouter les vinyles dans les années 50 à 80."),
    _q("o2", "objets-antan",
       "Quel objet servait à filer la laine à la maison ?",
       ["Un rouet", "Un métier à tisser", "Une quenouille", "Un dévidoir"], 0,
       "Le rouet était présent dans de nombreuses maisons rurales pour filer la laine ou le lin."),
    _q("o3", "objets-antan",
       "Qu'est-ce qu'une « TSF » ?",
       ["Un téléphone à cadran", "Une radio sans fil", "Un télégraphe", "Une machine à écrire"], 1,
       "TSF signifie « Télégraphie sans fil ». C'était le nom donné aux postes de radio dans la première moitié du XXᵉ siècle."),
    _q("o4", "objets-antan",
       "Quel ustensile servait à allumer le feu dans la cheminée ?",
       ["Un soufflet", "Un tisonnier", "Une braise", "Une chaufferette"], 0,
       "Le soufflet permettait d'envoyer de l'air sur les braises pour raviver le feu."),

    # Histoire de France
    _q("h1", "histoire-france",
       "En quelle année a eu lieu la prise de la Bastille ?",
       ["1788", "1789", "1791", "1793"], 1,
       "Le 14 juillet 1789, le peuple parisien prit la Bastille, événement fondateur de la Révolution française."),
    _q("h2", "histoire-france",
       "Qui était président de la République lors de l'appel du 18 juin 1940 ?",
       ["Albert Lebrun", "Paul Reynaud", "Édouard Daladier", "Philippe Pétain"], 0,
       "Albert Lebrun fut le dernier président de la IIIᵉ République. Le 18 juin 1940, c'est De Gaulle qui lance l'appel depuis Londres."),
    _q("h3", "histoire-france",
       "Sous quel roi a été construit le château de Versailles ?",
       ["Louis XIII", "Louis XIV", "Louis XV", "Louis XVI"], 1,
       "Louis XIV a fait agrandir le pavillon de chasse de son père pour en faire le palais royal en 1682."),
    _q("h4", "histoire-france",
       "En quelle année Charles de Gaulle est-il devenu président de la Vᵉ République ?",
       ["1945", "1958", "1962", "1969"], 1,
       "Le général de Gaulle est élu président par un collège électoral le 21 décembre 1958, puis au suffrage universel en 1965."),

    # Cuisine
    _q("cu1", "cuisine-terroir",
       "Quelle est la spécialité culinaire emblématique de la Provence ?",
       ["La bouillabaisse", "Le cassoulet", "La tartiflette", "Le pot-au-feu"], 0,
       "La bouillabaisse est la soupe de poissons emblématique de Marseille et de la Provence."),
    _q("cu2", "cuisine-terroir",
       "Avec quel fromage prépare-t-on traditionnellement la tartiflette ?",
       ["Le beaufort", "Le reblochon", "L'emmental", "Le comté"], 1,
       "La tartiflette savoyarde se prépare avec du reblochon, des pommes de terre, des oignons et des lardons."),
    _q("cu3", "cuisine-terroir",
       "Quelle ville est célèbre pour ses canelés ?",
       ["Bordeaux", "Toulouse", "Nantes", "Lyon"], 0,
       "Le canelé est une spécialité bordelaise à base de rhum et de vanille, à la croûte caramélisée."),
    _q("cu4", "cuisine-terroir",
       "Le kouign-amann est une pâtisserie traditionnelle de quelle région ?",
       ["Normandie", "Bretagne", "Alsace", "Pays Basque"], 1,
       "Le kouign-amann (« gâteau au beurre » en breton) est né à Douarnenez vers 1860."),
]
