"""Static seed data for Quiz d'Antan.

8 categories x ~30 questions = ~240 questions total.
"""

CATEGORIES = [
    {
        "id": "annees-50-60",
        "title": "Années 50-60",
        "description": "Télé, musique, événements et icônes des Trente Glorieuses.",
        "color": "#E07A5F", "icon": "tv",
        "mascot_image": "/api/static/mascots/annees-50-60.png",
        "mascot_name": "Robert le Téléspectateur", "count": 30,
    },
    {
        "id": "chansons", "title": "Chansons",
        "description": "Les grands succès d'Édith Piaf à Brassens, en passant par Trenet.",
        "color": "#722F37", "icon": "music",
        "mascot_image": "/api/static/mascots/chansons.png",
        "mascot_name": "Yvette la Chanteuse", "count": 30,
    },
    {
        "id": "cinema", "title": "Cinéma",
        "description": "Films cultes, acteurs inoubliables et répliques mythiques.",
        "color": "#1E3A5F", "icon": "film",
        "mascot_image": "/api/static/mascots/cinema.png",
        "mascot_name": "Marcel le Projectionniste", "count": 30,
    },
    {
        "id": "objets-antan", "title": "Objets d'antan",
        "description": "Saurez-vous reconnaître les objets d'autrefois ?",
        "color": "#F2CC8F", "icon": "phone",
        "mascot_image": "/api/static/mascots/objets-antan.png",
        "mascot_name": "Mémé Suzanne", "count": 30,
    },
    {
        "id": "histoire-france", "title": "Histoire de France",
        "description": "Événements marquants et grands personnages de notre histoire.",
        "color": "#3D9970", "icon": "landmark",
        "mascot_image": "/api/static/mascots/histoire-france.png",
        "mascot_name": "Maître Henri", "count": 30,
    },
    {
        "id": "cuisine-terroir", "title": "Cuisine & Terroir",
        "description": "Recettes, produits et traditions des régions de France.",
        "color": "#D97706", "icon": "utensils",
        "mascot_image": "/api/static/mascots/cuisine-terroir.png",
        "mascot_name": "Chef Bernard", "count": 30,
    },
    {
        "id": "culture-40-ans", "title": "Génération 40 ans",
        "description": "Pop culture, tech et événements des années 90 et 2000.",
        "color": "#8B5CF6", "icon": "sparkles",
        "mascot_image": "/api/static/mascots/culture-40-ans.png",
        "mascot_name": "Sophie la Quadra", "count": 30,
    },
    {
        "id": "culture-70-ans", "title": "Génération 70 ans",
        "description": "Culture générale des années 60-70 : société, sciences, monde.",
        "color": "#0F766E", "icon": "book",
        "mascot_image": "/api/static/mascots/culture-70-ans.png",
        "mascot_name": "Pierre le Sage", "count": 30,
    },
]


def Q(qid, cat, q, opts, correct, exp):
    return {"id": qid, "category_id": cat, "question": q, "options": opts, "correct_index": correct, "explanation": exp}


QUESTIONS = [
    # ============================ ANNÉES 50-60 (30) ============================
    Q("a1", "annees-50-60", "En quelle année la télévision française a-t-elle diffusé son premier journal télévisé ?",
      ["1949", "1954", "1959", "1962"], 0,
      "Le tout premier JT a été diffusé le 29 juin 1949 par la RTF."),
    Q("a2", "annees-50-60", "Quel cycliste français a remporté trois Tours de France consécutifs dans les années 1950 ?",
      ["Jacques Anquetil", "Louison Bobet", "Raymond Poulidor", "Roger Walkowiak"], 1,
      "Louison Bobet : Tours 1953, 1954 et 1955."),
    Q("a3", "annees-50-60", "Comment était surnommée la 2CV Citroën lancée en 1948 ?",
      ["La Coccinelle", "La Deudeuche", "La Quatrelle", "La Traction"], 1,
      "La 2CV était surnommée la « Deudeuche ». Produite jusqu'en 1990."),
    Q("a4", "annees-50-60", "Quel programme musical télévisé a été lancé en 1959 ?",
      ["Salut les copains", "Âge tendre et tête de bois", "Discorama", "Le Palmarès des chansons"], 1,
      "« Âge tendre et tête de bois » présenté par Albert Raisner."),
    Q("a5", "annees-50-60", "Qui a remporté la Coupe du monde de football en 1958 ?",
      ["Le Brésil", "La France", "La Suède", "L'Allemagne"], 0,
      "Premier titre mondial du Brésil, en Suède, grâce à un jeune Pelé."),
    Q("a6", "annees-50-60", "Quelle grande poupée française à la mode est lancée en 1957 ?",
      ["Bella", "Barbie", "Caroline", "Petitcollin"], 0,
      "La poupée Bella, fabriquée à Perpignan, a accompagné des générations d'enfants."),
    Q("a7", "annees-50-60", "Quel mouvement de mai 1968 a marqué la France ?",
      ["La grève des mineurs", "Les barricades étudiantes", "La marche des paysans", "La mutinerie"], 1,
      "Mai 68 : vaste mouvement initié par les étudiants au Quartier latin."),
    Q("a8", "annees-50-60", "Comment s'appelait le premier satellite français lancé en 1965 ?",
      ["Spoutnik", "Astérix", "Diamant", "Mercure"], 1,
      "Astérix, placé en orbite le 26 novembre 1965 par la fusée Diamant."),
    Q("a9", "annees-50-60", "Quel grand acteur populaire est décédé en 1970 ?",
      ["Bourvil", "Fernandel", "Louis de Funès", "Pierre Brasseur"], 0,
      "Bourvil est décédé le 23 septembre 1970."),
    Q("a10", "annees-50-60", "Quel chanteur s'est imposé avec « Souvenirs, souvenirs » en 1960 ?",
      ["Eddy Mitchell", "Johnny Hallyday", "Claude François", "Sacha Distel"], 1,
      "Johnny Hallyday : ce tube rock'n'roll a lancé sa carrière."),
    Q("a11", "annees-50-60", "Quelle marque française d'électroménager s'est imposée dans les années 50 avec ses cuisinières ?",
      ["Moulinex", "Calor", "Arthur Martin", "Brandt"], 2,
      "Arthur Martin a équipé des millions de cuisines françaises."),
    Q("a12", "annees-50-60", "Quel parfum mythique de Christian Dior est sorti en 1947 ?",
      ["N°5", "Miss Dior", "Shalimar", "L'Air du Temps"], 1,
      "Miss Dior accompagnait la collection « New Look » de 1947."),
    Q("a13", "annees-50-60", "Comment s'appelait le célèbre yéyé arrivé en France grâce à Salut les copains ?",
      ["Sheila", "Françoise Hardy", "Sylvie Vartan", "Toutes"], 3,
      "Salut les copains a propulsé Sheila, Hardy, Vartan et d'autres yéyés."),
    Q("a14", "annees-50-60", "Quel modèle Renault est sorti en 1961 et a démocratisé l'automobile familiale ?",
      ["Renault 4", "Renault 5", "Dauphine", "Renault 16"], 0,
      "La Renault 4 (« 4L »), produite à plus de 8 millions d'exemplaires."),
    Q("a15", "annees-50-60", "Qui a écrit « Bonjour tristesse », succès littéraire de 1954 ?",
      ["Marguerite Duras", "Françoise Sagan", "Simone de Beauvoir", "Colette"], 1,
      "Françoise Sagan a écrit ce roman à 18 ans, qui l'a rendue célèbre."),
    Q("a16", "annees-50-60", "Quel président américain a effectué une visite officielle en France en 1961 ?",
      ["Eisenhower", "Kennedy", "Nixon", "Johnson"], 1,
      "John F. Kennedy et Jackie sont reçus par le général de Gaulle en mai 1961."),
    Q("a17", "annees-50-60", "Quel humoriste a marqué la radio puis la télé avec « Au théâtre ce soir » ?",
      ["Bourvil", "Pierre Bellemare", "Jean Nohain", "Pierre Dac"], 1,
      "Pierre Bellemare a présenté de nombreuses émissions cultes."),
    Q("a18", "annees-50-60", "Qui a remporté Roland-Garros en 1956 et 1958 ?",
      ["Henri Cochet", "Jean Borotra", "Robert Haillet", "Aucun Français"], 3,
      "Aucun Français ne gagne RG en 1956-1958 : Lew Hoad puis Mervyn Rose."),
    Q("a19", "annees-50-60", "Quel président de la République a démissionné en 1969 ?",
      ["René Coty", "De Gaulle", "Pompidou", "Giscard"], 1,
      "Charles de Gaulle démissionne le 28 avril 1969 après son référendum perdu."),
    Q("a20", "annees-50-60", "Quel succès yéyé de Sheila est sorti en 1963 ?",
      ["L'École est finie", "Les Rois Mages", "Bang Bang", "Adios Amor"], 0,
      "« L'École est finie » a fait connaître Sheila à 17 ans."),
    Q("a21", "annees-50-60", "Quelle voiture italienne est devenue iconique dans les années 60 en France ?",
      ["Fiat 500", "Alfa Romeo", "Lancia", "Vespa"], 0,
      "La Fiat 500, lancée en 1957, séduit toute l'Europe."),
    Q("a22", "annees-50-60", "Quel jouet en plastique est arrivé en France dans les années 60 ?",
      ["Lego", "Meccano", "Playmobil", "Légo"], 0,
      "Lego, créé au Danemark en 1949, conquiert la France dans les années 60."),
    Q("a23", "annees-50-60", "Quel réalisateur français a marqué la Nouvelle Vague avec « Les 400 coups » ?",
      ["Truffaut", "Godard", "Chabrol", "Rohmer"], 0,
      "François Truffaut a réalisé ce film autobiographique en 1959."),
    Q("a24", "annees-50-60", "Quel sport a fait son apparition aux JO de Tokyo en 1964 ?",
      ["Le judo", "Le karaté", "Le tennis", "Le basket"], 0,
      "Le judo a été intégré aux JO en 1964 (Tokyo, terre natale du judo)."),
    Q("a25", "annees-50-60", "Comment s'appelait le ministre de la Culture sous de Gaulle ?",
      ["Pierre Mendès France", "André Malraux", "Maurice Druon", "Edgar Faure"], 1,
      "André Malraux, ministre de la Culture de 1959 à 1969."),
    Q("a26", "annees-50-60", "Quel produit alimentaire emblématique a été lancé en 1963 par Mont Blanc ?",
      ["La crème dessert", "Le yaourt", "Le pudding", "La mousse"], 0,
      "Mont Blanc, marque française historique des crèmes desserts."),
    Q("a27", "annees-50-60", "Quel chanteur québécois popularise « Mon Pays » en France dans les années 60 ?",
      ["Félix Leclerc", "Gilles Vigneault", "Robert Charlebois", "Aznavour"], 1,
      "Gilles Vigneault : « Mon Pays » (1965), un classique de la chanson québécoise."),
    Q("a28", "annees-50-60", "Quel grand magazine pour la jeunesse a été créé en 1959 ?",
      ["Pif Gadget", "Le Journal de Mickey", "Spirou", "Salut les Copains"], 3,
      "Salut les Copains, lancé en 1959, accompagne la génération yéyé."),
    Q("a29", "annees-50-60", "En quelle année a eu lieu la victoire de Diên Biên Phu ?",
      ["1952", "1954", "1956", "1958"], 1,
      "La défaite française de Diên Biên Phu le 7 mai 1954 met fin à l'Indochine française."),
    Q("a30", "annees-50-60", "Quel jeu télévisé célèbre est lancé en 1965 ?",
      ["Tournez Manège", "Intervilles", "Le Schmilblick", "Les Jeux de 20 heures"], 1,
      "Intervilles, créé par Guy Lux, mêle villes et épreuves loufoques (vachettes incluses)."),

    # ============================ CHANSONS (30) ============================
    Q("c1", "chansons", "Quel chanteur français a composé et interprété « La Mer » ?",
      ["Édith Piaf", "Charles Trenet", "Jacques Brel", "Georges Brassens"], 1,
      "Charles Trenet a composé « La Mer » en 1943, enregistrée en 1946."),
    Q("c2", "chansons", "Qui a interprété « La Vie en rose » en 1945 ?",
      ["Mireille Mathieu", "Édith Piaf", "Dalida", "Juliette Gréco"], 1,
      "Édith Piaf a écrit les paroles, son plus grand succès international."),
    Q("c3", "chansons", "« Ne me quitte pas » est de quel artiste ?",
      ["Léo Ferré", "Jacques Brel", "Serge Gainsbourg", "Aznavour"], 1,
      "Jacques Brel, composée en 1959."),
    Q("c4", "chansons", "Qui chantait « Les Champs-Élysées » en 1969 ?",
      ["Sacha Distel", "Joe Dassin", "Claude François", "Hugues Aufray"], 1,
      "Joe Dassin a fait de cette chanson un hit international."),
    Q("c5", "chansons", "Qui a écrit « La Bohème » en 1965 ?",
      ["Charles Aznavour", "Yves Montand", "Gilbert Bécaud", "Serge Reggiani"], 0,
      "Charles Aznavour avec Jacques Plante, évoquant Montmartre."),
    Q("c6", "chansons", "Qui a popularisé « Les copains d'abord » en 1964 ?",
      ["Georges Brassens", "Léo Ferré", "Hugues Aufray", "Jacques Brel"], 0,
      "Georges Brassens, écrit pour un film d'Yves Robert."),
    Q("c7", "chansons", "Quelle chanteuse fut surnommée « la môme » ?",
      ["Mireille Mathieu", "Édith Piaf", "Dalida", "Barbara"], 1,
      "Édith Piaf, repérée chantant dans la rue."),
    Q("c8", "chansons", "Qui a écrit « Comme d'habitude » repris par Sinatra ?",
      ["Joe Dassin", "Claude François", "Michel Sardou", "Eddy Mitchell"], 1,
      "Claude François a coécrit ce titre devenu « My Way »."),
    Q("c9", "chansons", "Qui interprète « Capri c'est fini » en 1965 ?",
      ["Hervé Vilard", "Adamo", "Antoine", "Christophe"], 0,
      "Hervé Vilard, succès retentissant à 19 ans."),
    Q("c10", "chansons", "Quelle chanson de Dalida en duo avec Delon est sortie en 1973 ?",
      ["Bambino", "Gigi l'Amoroso", "Paroles, paroles", "Mourir sur scène"], 2,
      "« Paroles, paroles » avec Alain Delon est devenu un classique."),
    Q("c11", "chansons", "Qui chante « Tombe la neige » ?",
      ["Adamo", "Aznavour", "Bécaud", "Dassin"], 0,
      "Salvatore Adamo a popularisé cette ballade en 1963."),
    Q("c12", "chansons", "Qui interprète « Tous les garçons et les filles » ?",
      ["Sheila", "Françoise Hardy", "Sylvie Vartan", "Petula Clark"], 1,
      "Françoise Hardy, premier succès à 18 ans en 1962."),
    Q("c13", "chansons", "Quelle chanson est l'hymne anti-guerre de Boris Vian ?",
      ["Le Déserteur", "La Java", "Je bois", "J'suis snob"], 0,
      "« Le Déserteur » (1954), longtemps censurée à la radio."),
    Q("c14", "chansons", "Qui chante « Et maintenant » en 1961 ?",
      ["Gilbert Bécaud", "Charles Aznavour", "Yves Montand", "Sacha Distel"], 0,
      "Gilbert Bécaud, « What Now My Love » en anglais, immense succès."),
    Q("c15", "chansons", "Qui interprète « La Javanaise » composée pour elle par Gainsbourg ?",
      ["Juliette Gréco", "Brigitte Bardot", "Jane Birkin", "France Gall"], 0,
      "Juliette Gréco, en 1963 — Gainsbourg lui a offert la chanson."),
    Q("c16", "chansons", "Qui chante « Poupée de cire, poupée de son » à l'Eurovision 1965 ?",
      ["Sheila", "Sylvie Vartan", "France Gall", "Dalida"], 2,
      "France Gall, victoire pour le Luxembourg avec une chanson de Gainsbourg."),
    Q("c17", "chansons", "Qui chante « Le métèque » en 1969 ?",
      ["Georges Moustaki", "Léo Ferré", "Reggiani", "Brel"], 0,
      "Georges Moustaki, sa chanson la plus connue."),
    Q("c18", "chansons", "Quelle chanson de Brel évoque le port d'Amsterdam ?",
      ["Le Plat Pays", "Amsterdam", "Marieke", "Quand on n'a que l'amour"], 1,
      "« Amsterdam » (1964), créée à l'Olympia, monument du répertoire."),
    Q("c19", "chansons", "Qui chante « Les Lacs du Connemara » ?",
      ["Michel Sardou", "Joe Dassin", "Renaud", "Cabrel"], 0,
      "Michel Sardou, succès intemporel sorti en 1981."),
    Q("c20", "chansons", "Qui interprète « Mistral gagnant » en 1985 ?",
      ["Francis Cabrel", "Renaud", "Jean-Jacques Goldman", "Yves Duteil"], 1,
      "Renaud, chanson tendre dédiée à sa fille Lolita."),
    Q("c21", "chansons", "Qui chante « Je t'aime moi non plus » avec Gainsbourg en 1969 ?",
      ["Brigitte Bardot", "Jane Birkin", "Catherine Deneuve", "Marianne Faithfull"], 1,
      "Jane Birkin, après un premier enregistrement avec Bardot."),
    Q("c22", "chansons", "Qui est l'auteur-compositeur de « L'aigle noir » ?",
      ["Barbara", "Véronique Sanson", "Anne Sylvestre", "Catherine Lara"], 0,
      "Barbara, chanson au sens intime profond (1970)."),
    Q("c23", "chansons", "Quelle chanson de Reggiani évoque les loups ?",
      ["Les loups sont entrés dans Paris", "Le petit garçon", "Sarah", "Ma fille"], 0,
      "« Les loups sont entrés dans Paris » (1967), métaphore de Mai 68."),
    Q("c24", "chansons", "Qui chante « Marylou » et « Manureva » dans les années 70 ?",
      ["Alain Souchon", "Renaud", "Cabrel", "Christophe"], 0,
      "Alain Souchon, avec Laurent Voulzy à la composition."),
    Q("c25", "chansons", "Qui chante « Magnolias for Ever » ?",
      ["Claude François", "Michel Sardou", "Pascal Sevran", "Sheila"], 0,
      "Claude François, sortie en 1977, un an avant son décès."),
    Q("c26", "chansons", "Qui interprète « Cargo de nuit » en 1989 ?",
      ["Axel Bauer", "Étienne Daho", "Indochine", "Niagara"], 1,
      "Étienne Daho, hit majeur de la fin des années 80."),
    Q("c27", "chansons", "Qui chante « Quand on a que l'amour » ?",
      ["Brel", "Brassens", "Aznavour", "Ferré"], 0,
      "Jacques Brel, en 1956, son premier vrai succès."),
    Q("c28", "chansons", "Qui chante « Comment te dire adieu » écrite par Gainsbourg ?",
      ["Sheila", "Françoise Hardy", "France Gall", "Sylvie Vartan"], 1,
      "Françoise Hardy en 1968, paroles signées Gainsbourg."),
    Q("c29", "chansons", "Quel chanteur belge a écrit « Ces gens-là » ?",
      ["Brel", "Adamo", "Stromae", "Arno"], 0,
      "Jacques Brel, monologue chanté féroce sorti en 1966."),
    Q("c30", "chansons", "Qui chante « Les Mots bleus » composé par Daniel Bevilacqua ?",
      ["Christophe", "Dassin", "Aznavour", "Polnareff"], 0,
      "Christophe (vrai nom Daniel Bevilacqua), 1974."),

    # ============================ CINÉMA (30) ============================
    Q("ci1", "cinema", "Dans quel film de 1956 Brigitte Bardot devient une icône ?",
      ["Et Dieu… créa la femme", "En cas de malheur", "La Vérité", "Le Mépris"], 0,
      "Roger Vadim a fait de Bardot un mythe avec ce film."),
    Q("ci2", "cinema", "Qui réalise « Les Tontons flingueurs » (1963) ?",
      ["Henri Verneuil", "Georges Lautner", "Claude Sautet", "Gérard Oury"], 1,
      "Georges Lautner, dialogues de Michel Audiard."),
    Q("ci3", "cinema", "Quel duo joue dans « La Grande Vadrouille » ?",
      ["Bourvil et De Funès", "Belmondo et Delon", "Gabin et Fernandel", "Ventura et Belmondo"], 0,
      "Louis de Funès et Bourvil, film de Gérard Oury (1966)."),
    Q("ci4", "cinema", "Dans quel film Gabin traverse Paris avec une cargaison de viande ?",
      ["La Traversée de Paris", "Le Cave se rebiffe", "Le Pacha", "Archimède le clochard"], 0,
      "« La Traversée de Paris » (1956), avec Bourvil."),
    Q("ci5", "cinema", "Qui réalise « À bout de souffle » en 1960 ?",
      ["François Truffaut", "Jean-Luc Godard", "Claude Chabrol", "Éric Rohmer"], 1,
      "Jean-Luc Godard, manifeste de la Nouvelle Vague."),
    Q("ci6", "cinema", "Combien de Césars « Le Dernier Métro » a-t-il reçus en 1981 ?",
      ["5", "8", "10", "12"], 2,
      "Le film de Truffaut a remporté 10 Césars sur 12 nominations."),
    Q("ci7", "cinema", "Quel film de 1990 a triomphé avec Depardieu en gentilhomme au grand nez ?",
      ["Cyrano de Bergerac", "Le Hussard sur le toit", "Camille Claudel", "Tous les matins du monde"], 0,
      "« Cyrano de Bergerac » de Rappeneau, 10 Césars."),
    Q("ci8", "cinema", "Qui réalise « Le Fabuleux Destin d'Amélie Poulain » en 2001 ?",
      ["Luc Besson", "Jean-Pierre Jeunet", "Mathieu Kassovitz", "Claude Berri"], 1,
      "Jean-Pierre Jeunet, avec Audrey Tautou."),
    Q("ci9", "cinema", "Coluche a reçu le César du meilleur acteur en 1984 pour quel film ?",
      ["Tchao Pantin", "L'Aile ou la Cuisse", "Banzaï", "Inspecteur la Bavure"], 0,
      "« Tchao Pantin » de Claude Berri, rôle dramatique majeur."),
    Q("ci10", "cinema", "Qui réalise « La Vie est belle » (1997) ?",
      ["Roberto Benigni", "Federico Fellini", "Giuseppe Tornatore", "Bernardo Bertolucci"], 0,
      "Roberto Benigni, 3 Oscars dont meilleur acteur."),
    Q("ci11", "cinema", "Dans quel film Belmondo joue-t-il un cascadeur amoureux ?",
      ["L'Homme de Rio", "Le Magnifique", "Itinéraire d'un enfant gâté", "Le Professionnel"], 0,
      "« L'Homme de Rio » de Philippe de Broca (1964)."),
    Q("ci12", "cinema", "Quel film de Visconti met en scène Alain Delon en 1963 ?",
      ["Rocco et ses frères", "Le Guépard", "Mort à Venise", "L'Innocent"], 1,
      "« Le Guépard », avec Delon dans le rôle de Tancredi."),
    Q("ci13", "cinema", "Qui réalise « Les Parapluies de Cherbourg » en 1964 ?",
      ["Claude Lelouch", "Jacques Demy", "Agnès Varda", "Jean-Pierre Mocky"], 1,
      "Jacques Demy, musique de Michel Legrand, Palme d'Or."),
    Q("ci14", "cinema", "Quel acteur français a interprété James Bond ?",
      ["Belmondo", "Delon", "Lambert Wilson", "Aucun"], 3,
      "Aucun acteur français n'a interprété James Bond officiellement."),
    Q("ci15", "cinema", "Quel film de Lelouch a remporté la Palme d'Or en 1966 ?",
      ["Un homme et une femme", "Vivre pour vivre", "Itinéraire d'un enfant gâté", "L'Aventure"], 0,
      "« Un homme et une femme » avec Anouk Aimée et Trintignant."),
    Q("ci16", "cinema", "Qui réalise « Mon Oncle » (1958) ?",
      ["Jacques Tati", "Pierre Étaix", "René Clair", "Jacques Rivette"], 0,
      "Jacques Tati, Oscar du meilleur film étranger 1959."),
    Q("ci17", "cinema", "Quel acteur joue le rôle-titre dans « Le Vieux Fusil » (1975) ?",
      ["Philippe Noiret", "Lino Ventura", "Yves Montand", "Romy Schneider"], 0,
      "Philippe Noiret avec Romy Schneider, drame poignant sur l'Occupation."),
    Q("ci18", "cinema", "Quel film de Jean Renoir est considéré comme un chef-d'œuvre antimilitariste ?",
      ["La Bête humaine", "La Grande Illusion", "La Règle du jeu", "French Cancan"], 1,
      "« La Grande Illusion » (1937), avec Gabin et Pierre Fresnay."),
    Q("ci19", "cinema", "Qui réalise « La Boum » en 1980 ?",
      ["Claude Berri", "Claude Pinoteau", "Yves Robert", "Édouard Molinaro"], 1,
      "Claude Pinoteau, succès qui révèle Sophie Marceau à 13 ans."),
    Q("ci20", "cinema", "Qui réalise « Le Salaire de la peur » en 1953 ?",
      ["Jean Renoir", "Henri-Georges Clouzot", "René Clément", "Marcel Carné"], 1,
      "Henri-Georges Clouzot, Palme d'Or à Cannes."),
    Q("ci21", "cinema", "Quel film d'Étienne Chatiliez a triomphé en 1988 ?",
      ["La vie est un long fleuve tranquille", "Tatie Danielle", "Le Bonheur est dans le pré", "Tanguy"], 0,
      "« La vie est un long fleuve tranquille », 4 Césars."),
    Q("ci22", "cinema", "Quel film de Sautet réunit Romy Schneider et Yves Montand ?",
      ["César et Rosalie", "Les choses de la vie", "Vincent, François, Paul et les autres", "Garçon !"], 0,
      "« César et Rosalie » (1972)."),
    Q("ci23", "cinema", "Qui réalise « Le Cercle rouge » en 1970 ?",
      ["Jean-Pierre Melville", "Henri Verneuil", "Yves Boisset", "Costa-Gavras"], 0,
      "Jean-Pierre Melville, avec Delon, Bourvil et Volonté."),
    Q("ci24", "cinema", "Dans quel film De Funès joue-t-il un chef d'orchestre ?",
      ["Le Grand Restaurant", "La Folie des grandeurs", "La Grande Vadrouille", "La 7ème compagnie"], 0,
      "Dans « Le Grand Restaurant » De Funès joue Septime, restaurateur excentrique."),
    Q("ci25", "cinema", "Quel film de Sergio Leone met en scène Charles Bronson ?",
      ["Il était une fois dans l'Ouest", "Le Bon, la Brute et le Truand", "Pour une poignée de dollars", "Et pour quelques dollars de plus"], 0,
      "« Il était une fois dans l'Ouest » (1968), avec Bronson et Cardinale."),
    Q("ci26", "cinema", "Quel film a fait connaître Catherine Deneuve à 21 ans ?",
      ["Les Parapluies de Cherbourg", "Belle de jour", "Tristana", "Le Sauvage"], 0,
      "« Les Parapluies de Cherbourg » (1964), Palme d'Or."),
    Q("ci27", "cinema", "Qui réalise « Mon Oncle d'Amérique » (1980) ?",
      ["Alain Resnais", "Louis Malle", "Patrice Leconte", "Bertrand Tavernier"], 0,
      "Alain Resnais, prix spécial du jury à Cannes."),
    Q("ci28", "cinema", "Quel acteur, surnommé « Le Magnifique », est mort en 2021 ?",
      ["Belmondo", "Delon", "Piccoli", "Marielle"], 0,
      "Jean-Paul Belmondo est décédé le 6 septembre 2021."),
    Q("ci29", "cinema", "Qui réalise « Le Père Noël est une ordure » (1982) ?",
      ["Jean-Marie Poiré", "Patrice Leconte", "Francis Veber", "Coluche"], 0,
      "Jean-Marie Poiré, adapté de la pièce du Splendid."),
    Q("ci30", "cinema", "Dans quel film Hitchcock met-il en scène une douche tragique ?",
      ["Psychose", "Sueurs froides", "Les Oiseaux", "Fenêtre sur cour"], 0,
      "« Psychose » (1960), scène de douche restée mythique."),

    # ============================ OBJETS D'ANTAN (30) ============================
    Q("o1", "objets-antan", "Comment appelle-t-on l'appareil pour écouter les vinyles ?",
      ["Un magnétoscope", "Un électrophone", "Un gramophone", "Un transistor"], 1,
      "L'électrophone (ou tourne-disque) lisait les vinyles."),
    Q("o2", "objets-antan", "Quel objet servait à filer la laine ?",
      ["Un rouet", "Un métier à tisser", "Une quenouille", "Un dévidoir"], 0,
      "Le rouet, présent dans de nombreuses maisons rurales."),
    Q("o3", "objets-antan", "Que signifie « TSF » ?",
      ["Téléphonie sans frais", "Télégraphie sans fil", "Tube sans fond", "Téléviseur sans fil"], 1,
      "TSF : « Télégraphie sans fil », les premières radios."),
    Q("o4", "objets-antan", "Quel ustensile servait à allumer la cheminée ?",
      ["Un soufflet", "Un tisonnier", "Une chaufferette", "Un sabot"], 0,
      "Le soufflet envoyait de l'air sur les braises."),
    Q("o5", "objets-antan", "Comment conservait-on le lait avant le frigo ?",
      ["Glacière à blocs", "Cave fraîche", "Jarre en terre", "Toutes ces solutions"], 3,
      "Tous ces moyens étaient utilisés avant le réfrigérateur."),
    Q("o6", "objets-antan", "Quel récipient transportait le lait à la ferme ?",
      ["Un broc", "Un bidon", "Une bouteille", "Une jarre"], 1,
      "Le bidon métallique du laitier."),
    Q("o7", "objets-antan", "Quel objet indiquait la pression atmosphérique ?",
      ["Un baromètre", "Une pendule", "Un thermomètre", "Une girouette"], 0,
      "Le baromètre, souvent décoré, indiquait beau temps ou orage."),
    Q("o8", "objets-antan", "Comment s'appelle l'appareil à manivelle pour repasser ?",
      ["Un fer à charbon", "Une calandre", "Une essoreuse", "Un repassoir"], 1,
      "La calandre lissait les draps entre deux rouleaux."),
    Q("o9", "objets-antan", "Quel objet en bois lavait le linge au lavoir ?",
      ["Un battoir", "Un manche à balai", "Une planche", "Une louche"], 0,
      "Le battoir en bois dur frappait le linge pour le nettoyer."),
    Q("o10", "objets-antan", "Quel son rythmait la journée du village ?",
      ["Le clairon", "La cloche", "Le tambour", "La corne"], 1,
      "Les cloches de l'église : angélus, messes et heures."),
    Q("o11", "objets-antan", "Comment s'appelait le porte-plume utilisé à l'école ?",
      ["Plume Sergent-Major", "Plume Bic", "Plume Waterman", "Plume Pelikan"], 0,
      "La plume Sergent-Major a équipé des générations d'écoliers."),
    Q("o12", "objets-antan", "Quel objet servait à porter l'eau du puits ?",
      ["Une seille", "Un seau", "Une amphore", "Un baquet"], 0,
      "La seille (récipient en bois cerclé) ou le seau métallique."),
    Q("o13", "objets-antan", "Comment appelle-t-on les sabots en bois portés à la campagne ?",
      ["Galoches", "Sabots", "Patins", "Babouches"], 1,
      "Les sabots, taillés dans un seul bloc de bois, étaient courants."),
    Q("o14", "objets-antan", "Que désignait le mot « buvard » à l'école ?",
      ["Un papier absorbant", "Une boisson", "Un cahier", "Un crayon"], 0,
      "Le buvard absorbait l'excédent d'encre des plumes."),
    Q("o15", "objets-antan", "Quel meuble servait à conserver les aliments au frais ?",
      ["Le garde-manger", "La huche", "Le buffet", "L'armoire"], 0,
      "Le garde-manger, parfois suspendu, protégeait les aliments."),
    Q("o16", "objets-antan", "Comment s'appelait la lampe à pétrole de la cuisine ?",
      ["Une bougie", "Une lampe-tempête", "Une lampe Pigeon", "Une calbombe"], 2,
      "La lampe Pigeon, modèle français célèbre dès 1884."),
    Q("o17", "objets-antan", "Quel ustensile servait à moudre le café ?",
      ["Un mortier", "Un moulin à café", "Une râpe", "Un piston"], 1,
      "Le moulin à café Peugeot, à manivelle, équipait les cuisines."),
    Q("o18", "objets-antan", "Comment appelle-t-on l'objet à poignée pour battre les œufs ?",
      ["Un fouet", "Un mixeur", "Un batteur", "Une cuillère"], 0,
      "Le fouet, en métal ou en bois, indispensable en cuisine."),
    Q("o19", "objets-antan", "Quel ustensile servait à essorer la salade ?",
      ["Le panier à salade", "L'essoreuse", "Le tamis", "Le saladier"], 0,
      "Le panier en grillage qu'on faisait tourner dehors."),
    Q("o20", "objets-antan", "Quel ustensile servait à pétrir la pâte à pain à la maison ?",
      ["Le pétrin", "La maie", "La huche", "Le saloir"], 0,
      "Le pétrin, en bois ou en pierre, permettait de pétrir la pâte avant cuisson."),
    Q("o21", "objets-antan", "Comment s'appelait le portefeuille à monnaie ?",
      ["Une bourse", "Un porte-monnaie", "Un escarcelle", "Tous ces noms"], 3,
      "La bourse, le porte-monnaie ou l'escarcelle — selon les régions."),
    Q("o22", "objets-antan", "Quel objet fournissait l'éclairage dans la mine ?",
      ["Une lampe Davy", "Une bougie", "Une torche", "Une chandelle"], 0,
      "La lampe Davy, à filtre métallique, prévenait les explosions de grisou."),
    Q("o23", "objets-antan", "Quel objet servait à transporter la viande à la boucherie ?",
      ["Un panier", "Un crochet", "Une planche", "Un torchon"], 0,
      "Le panier, parfois doublé de toile cirée."),
    Q("o24", "objets-antan", "Comment s'appelait le bain familial du samedi soir ?",
      ["Le tub", "La baignoire en zinc", "Le baquet", "Tous ces noms"], 3,
      "Tub, baignoire en zinc ou baquet : le bain familial était hebdomadaire."),
    Q("o25", "objets-antan", "Quel objet sonnait pour appeler les domestiques ?",
      ["Une clochette", "Un gong", "Un sifflet", "Une trompette"], 0,
      "La clochette de table, présente dans les maisons bourgeoises."),
    Q("o26", "objets-antan", "Comment s'appelait l'ustensile pour battre les tapis ?",
      ["Un battoir à tapis", "Un balai", "Une raclette", "Une brosse"], 0,
      "Le battoir à tapis en osier ou bambou, utilisé sur la corde à linge."),
    Q("o27", "objets-antan", "Quel objet rangeait les boutons de la couturière ?",
      ["La boîte à boutons", "La trousse", "Le coffret", "L'étui"], 0,
      "La boîte à boutons, souvent une vieille boîte de biscuits réutilisée."),
    Q("o28", "objets-antan", "Quel objet utilisait-on pour couper le sucre vendu en pains coniques ?",
      ["Une pince à sucre", "Un casse-sucre", "Un marteau", "Un couteau de cuisine"], 1,
      "Le casse-sucre, sorte de petite guillotine à main, débitait le pain de sucre."),
    Q("o29", "objets-antan", "Comment s'appelait la pelle à charbon ?",
      ["La louchette", "La pellette", "L'écope", "La pelle à feu"], 3,
      "La pelle à feu servait à charger le poêle en charbon ou bois."),
    Q("o30", "objets-antan", "Quel ustensile faisait griller le pain dans la cheminée ?",
      ["Le grille-pain à manche", "Le pic", "La fourchette", "La pince"], 0,
      "Le grille-pain à long manche en fer forgé."),

    # ============================ HISTOIRE DE FRANCE (30) ============================
    Q("h1", "histoire-france", "En quelle année a eu lieu la prise de la Bastille ?",
      ["1788", "1789", "1791", "1793"], 1,
      "Le 14 juillet 1789, début de la Révolution française."),
    Q("h2", "histoire-france", "Qui était président lors de l'appel du 18 juin 1940 ?",
      ["Albert Lebrun", "Paul Reynaud", "Édouard Daladier", "Philippe Pétain"], 0,
      "Albert Lebrun, dernier président de la IIIᵉ République."),
    Q("h3", "histoire-france", "Sous quel roi Versailles devient-il palais royal ?",
      ["Louis XIII", "Louis XIV", "Louis XV", "Louis XVI"], 1,
      "Louis XIV s'installe à Versailles en 1682."),
    Q("h4", "histoire-france", "Quand de Gaulle devient-il président de la Vᵉ République ?",
      ["1945", "1958", "1962", "1969"], 1,
      "De Gaulle est élu président le 21 décembre 1958."),
    Q("h5", "histoire-france", "Qui couronne Napoléon empereur en 1804 ?",
      ["Le pape", "Lui-même", "Joséphine", "Talleyrand"], 1,
      "Napoléon se couronne lui-même à Notre-Dame en présence du pape Pie VII."),
    Q("h6", "histoire-france", "Quelle bataille marque la fin de Napoléon en 1815 ?",
      ["Austerlitz", "Iéna", "Waterloo", "Trafalgar"], 2,
      "Waterloo, défaite face aux Anglo-Prussiens en Belgique."),
    Q("h7", "histoire-france", "Qui était Jeanne d'Arc ?",
      ["Une princesse", "Une bergère devenue chef de guerre", "Une reine", "Une mère supérieure"], 1,
      "Jeune bergère lorraine, elle mena les armées sous Charles VII."),
    Q("h8", "histoire-france", "Quand la France a-t-elle aboli l'esclavage définitivement ?",
      ["1789", "1815", "1848", "1865"], 2,
      "Décret de Victor Schœlcher, 27 avril 1848."),
    Q("h9", "histoire-france", "Quel président a instauré les congés payés en 1936 ?",
      ["Léon Blum", "Édouard Daladier", "Albert Lebrun", "Paul Reynaud"], 0,
      "Léon Blum, Front populaire : 15 jours de congés payés."),
    Q("h10", "histoire-france", "Qui est le « Roi-Soleil » ?",
      ["Louis XIII", "Louis XIV", "Louis XV", "Henri IV"], 1,
      "Louis XIV (1643-1715), règne de 72 ans."),
    Q("h11", "histoire-france", "Quel roi a édicté l'Édit de Nantes en 1598 ?",
      ["Henri III", "Henri IV", "Louis XIII", "François Iᵉʳ"], 1,
      "Henri IV, l'édit accordait la liberté de culte aux protestants."),
    Q("h12", "histoire-france", "Qui a révoqué l'Édit de Nantes en 1685 ?",
      ["Louis XIII", "Louis XIV", "Louis XV", "Louis XVI"], 1,
      "Louis XIV, provoquant l'exil de 200 000 protestants."),
    Q("h13", "histoire-france", "Qui était Vercingétorix ?",
      ["Roi mérovingien", "Chef gaulois", "Empereur romain", "Roi franc"], 1,
      "Chef arverne qui résista à César, vaincu à Alésia en 52 av. J.-C."),
    Q("h14", "histoire-france", "Quelle reine est associée à la formule « Qu'ils mangent de la brioche » ?",
      ["Catherine de Médicis", "Marie-Antoinette", "Anne d'Autriche", "Marie de Médicis"], 1,
      "Phrase attribuée à tort à Marie-Antoinette (1755-1793)."),
    Q("h15", "histoire-france", "Quel président a démissionné en 1969 ?",
      ["René Coty", "De Gaulle", "Pompidou", "Giscard"], 1,
      "De Gaulle, après l'échec du référendum d'avril 1969."),
    Q("h16", "histoire-france", "En quelle année la guerre d'Algérie a-t-elle pris fin ?",
      ["1958", "1960", "1962", "1965"], 2,
      "Accords d'Évian le 18 mars 1962, indépendance le 5 juillet."),
    Q("h17", "histoire-france", "Quel président a lancé le TGV ?",
      ["Pompidou", "Giscard", "Mitterrand", "Chirac"], 2,
      "Le TGV Paris-Lyon a été inauguré par Mitterrand le 22 septembre 1981."),
    Q("h18", "histoire-france", "Qui a écrit la Déclaration des droits de l'homme et du citoyen ?",
      ["Robespierre", "Mirabeau", "L'Assemblée nationale constituante", "Voltaire"], 2,
      "Adoptée par l'Assemblée le 26 août 1789."),
    Q("h19", "histoire-france", "Quel roi a perdu la tête en 1793 ?",
      ["Louis XV", "Louis XVI", "Charles X", "Louis-Philippe"], 1,
      "Louis XVI, guillotiné le 21 janvier 1793 place de la Révolution."),
    Q("h20", "histoire-france", "Quelle bataille de 1916 a duré 300 jours ?",
      ["Verdun", "La Marne", "La Somme", "Ypres"], 0,
      "La bataille de Verdun (1916), symbole du sacrifice des poilus."),
    Q("h21", "histoire-france", "Qui était Charlemagne ?",
      ["Roi des Francs et empereur", "Roi de France", "Empereur romain", "Roi des Wisigoths"], 0,
      "Couronné empereur d'Occident en 800 par le pape Léon III."),
    Q("h22", "histoire-france", "En quelle année le mur de Berlin est-il tombé ?",
      ["1985", "1987", "1989", "1991"], 2,
      "Le 9 novembre 1989, événement majeur de la fin de la guerre froide."),
    Q("h23", "histoire-france", "Quel roi français a perdu la guerre de Cent Ans ?",
      ["Charles VI", "Charles VII", "Aucun, la France a gagné", "Louis XI"], 2,
      "La France gagne sous Charles VII en 1453."),
    Q("h24", "histoire-france", "Qui était président de la République lors du Front populaire ?",
      ["Albert Lebrun", "Gaston Doumergue", "Paul Doumer", "Alexandre Millerand"], 0,
      "Albert Lebrun, président de 1932 à 1940."),
    Q("h25", "histoire-france", "Quel territoire la France a-t-elle perdu en 1871 ?",
      ["L'Algérie", "L'Alsace-Lorraine", "La Corse", "Le Maroc"], 1,
      "Perte de l'Alsace-Moselle au traité de Francfort, après la guerre franco-prussienne."),
    Q("h26", "histoire-france", "Quel président français a aboli la peine de mort ?",
      ["Giscard", "Mitterrand", "Chirac", "Pompidou"], 1,
      "François Mitterrand, loi du 9 octobre 1981 portée par Robert Badinter."),
    Q("h27", "histoire-france", "Quelle dynastie régna sur la France jusqu'en 987 ?",
      ["Mérovingiens", "Carolingiens", "Capétiens", "Valois"], 1,
      "Les Carolingiens, descendants de Charlemagne. Hugues Capet est élu en 987."),
    Q("h28", "histoire-france", "Quel président est mort en exercice le 2 avril 1974 ?",
      ["De Gaulle", "Pompidou", "Giscard", "Mitterrand"], 1,
      "Georges Pompidou est décédé à l'Élysée des suites d'une maladie."),
    Q("h29", "histoire-france", "Quand la Vᵉ République a-t-elle été instaurée ?",
      ["1944", "1946", "1958", "1962"], 2,
      "Constitution adoptée par référendum le 28 septembre 1958."),
    Q("h30", "histoire-france", "Quel philosophe est associé aux Lumières et au « siècle de... » ?",
      ["Descartes", "Voltaire", "Pascal", "Rousseau"], 1,
      "Voltaire (1694-1778), figure majeure du Siècle des Lumières."),

    # ============================ CUISINE & TERROIR (30) ============================
    Q("cu1", "cuisine-terroir", "Spécialité culinaire emblématique de la Provence ?",
      ["La bouillabaisse", "Le cassoulet", "La tartiflette", "Le pot-au-feu"], 0,
      "La bouillabaisse, soupe de poissons marseillaise."),
    Q("cu2", "cuisine-terroir", "Quel fromage est utilisé dans la tartiflette ?",
      ["Le beaufort", "Le reblochon", "L'emmental", "Le comté"], 1,
      "Le reblochon, fromage savoyard AOP."),
    Q("cu3", "cuisine-terroir", "Quelle ville est célèbre pour ses canelés ?",
      ["Bordeaux", "Toulouse", "Nantes", "Lyon"], 0,
      "Le canelé bordelais, à base de rhum et vanille."),
    Q("cu4", "cuisine-terroir", "Le kouign-amann vient de quelle région ?",
      ["Normandie", "Bretagne", "Alsace", "Pays Basque"], 1,
      "Bretagne (Douarnenez, vers 1860). « Gâteau au beurre » en breton."),
    Q("cu5", "cuisine-terroir", "De quelle ville le cassoulet est-il une spécialité ?",
      ["Toulouse", "Castelnaudary", "Carcassonne", "Toutes ces villes"], 3,
      "Les trois villes se disputent la paternité du cassoulet."),
    Q("cu6", "cuisine-terroir", "Quel vin sucré accompagne le foie gras ?",
      ["Bordeaux", "Sauternes", "Champagne", "Beaujolais"], 1,
      "Le Sauternes, vin liquoreux, accord classique."),
    Q("cu7", "cuisine-terroir", "Origine du fromage Roquefort ?",
      ["Aveyron", "Lozère", "Cantal", "Lot"], 0,
      "Roquefort-sur-Soulzon (Aveyron), grottes naturelles."),
    Q("cu8", "cuisine-terroir", "Quel plat lyonnais est une panse de veau panée ?",
      ["La rosette", "Le tablier de sapeur", "La salade lyonnaise", "Les pommes lyonnaises"], 1,
      "Le tablier de sapeur, gras-double pané et frit."),
    Q("cu9", "cuisine-terroir", "Ingrédient principal de la ratatouille niçoise ?",
      ["Le chou", "L'aubergine", "La courgette", "La tomate"], 1,
      "L'aubergine, avec courgette, tomate et poivron."),
    Q("cu10", "cuisine-terroir", "Que sont les bredele ?",
      ["Biscuits alsaciens", "Crêpes bretonnes", "Petits pains", "Fruits confits"], 0,
      "Petits biscuits alsaciens de Noël."),
    Q("cu11", "cuisine-terroir", "Quel vin produit-on en Champagne ?",
      ["Vin tranquille uniquement", "Vin effervescent uniquement", "Les deux", "Aucun"], 2,
      "Vin effervescent (champagne) et vin tranquille (coteaux champenois)."),
    Q("cu12", "cuisine-terroir", "Le pastis est une boisson de quelle région ?",
      ["Bourgogne", "Provence", "Alsace", "Bretagne"], 1,
      "Le pastis, boisson anisée typique de Marseille."),
    Q("cu13", "cuisine-terroir", "Quelle est la spécialité de Nice à base de farine de pois chiches ?",
      ["La pissaladière", "La socca", "La pichade", "La fougasse"], 1,
      "La socca, galette niçoise, cuite au feu de bois."),
    Q("cu14", "cuisine-terroir", "D'où vient la moutarde la plus connue de France ?",
      ["Reims", "Dijon", "Strasbourg", "Lille"], 1,
      "La moutarde de Dijon, IGP, à base de graines noires."),
    Q("cu15", "cuisine-terroir", "Quelle est l'origine de la galette des Rois (frangipane) ?",
      ["Bretagne", "Provence", "Île-de-France", "Toute la France"], 2,
      "Tradition francilienne, étendue à toute la France."),
    Q("cu16", "cuisine-terroir", "Quel ustensile japonais est utilisé pour la fondue savoyarde ?",
      ["Le caquelon", "Le wok", "La sauteuse", "La cocotte"], 0,
      "Le caquelon en céramique, posé sur un réchaud."),
    Q("cu17", "cuisine-terroir", "Quel fromage normand est emblématique ?",
      ["Camembert", "Munster", "Roquefort", "Saint-Marcellin"], 0,
      "Le camembert de Normandie, AOP depuis 1983."),
    Q("cu18", "cuisine-terroir", "Quelle pâtisserie a la forme d'une roue de bicyclette ?",
      ["Le Paris-Brest", "L'éclair", "Le Saint-Honoré", "Le millefeuille"], 0,
      "Le Paris-Brest, créé en 1910 en hommage à la course cycliste."),
    Q("cu19", "cuisine-terroir", "Quelle viande utilise-t-on pour le bœuf bourguignon ?",
      ["Bœuf et lardons", "Veau", "Mouton", "Cheval"], 0,
      "Bœuf, vin rouge, lardons, oignons et champignons."),
    Q("cu20", "cuisine-terroir", "La quiche lorraine traditionnelle contient quoi ?",
      ["Lardons et œufs", "Fromage", "Oignons et fromage", "Saumon"], 0,
      "Migaine d'œufs et de crème + lardons (sans fromage à l'origine)."),
    Q("cu21", "cuisine-terroir", "Quelle est l'origine de la choucroute ?",
      ["Alsace", "Lorraine", "Bourgogne", "Allemagne"], 0,
      "Alsace, chou fermenté servi avec charcuterie et pommes de terre."),
    Q("cu22", "cuisine-terroir", "Quelle ville est célèbre pour son pâté en croûte ?",
      ["Lyon", "Reims", "Pézenas", "Toutes ces villes"], 3,
      "Pâté en croûte : spécialité reprise dans plusieurs villes."),
    Q("cu23", "cuisine-terroir", "Quel cépage est utilisé pour le Beaujolais ?",
      ["Pinot noir", "Gamay", "Merlot", "Syrah"], 1,
      "Le Gamay, cépage emblématique du Beaujolais."),
    Q("cu24", "cuisine-terroir", "Origine du nougat ?",
      ["Montélimar", "Avignon", "Aix-en-Provence", "Toulon"], 0,
      "Le nougat de Montélimar, à base d'amandes et miel."),
    Q("cu25", "cuisine-terroir", "Quel poisson est traditionnel dans la bouillabaisse ?",
      ["Le rouget", "Le cabillaud", "Le saumon", "Le thon"], 0,
      "Rouget, rascasse, vive, congre et autres poissons de roche."),
    Q("cu26", "cuisine-terroir", "Comment appelle-t-on le pain rond plat alsacien sucré ?",
      ["Bredele", "Kougelhopf", "Mannele", "Strudel"], 2,
      "Le mannele (petit bonhomme), brioché, servi à la Saint-Nicolas."),
    Q("cu27", "cuisine-terroir", "Quelle huile est traditionnelle en Provence ?",
      ["Tournesol", "Olive", "Colza", "Pépins de raisin"], 1,
      "L'huile d'olive, base de la cuisine provençale."),
    Q("cu28", "cuisine-terroir", "Quel dessert vient de Pithiviers ?",
      ["Gâteau aux amandes", "Tarte aux pommes", "Charlotte", "Éclair"], 0,
      "Le pithiviers, feuilleté garni à la frangipane d'amande."),
    Q("cu29", "cuisine-terroir", "Quelle est la véritable origine du croissant ?",
      ["Paris", "Vienne (Autriche)", "Marseille", "Lille"], 1,
      "Inspiré du kipferl autrichien, francisé au XIXᵉ siècle."),
    Q("cu30", "cuisine-terroir", "Quelle ville est connue pour ses andouillettes ?",
      ["Troyes", "Lyon", "Cambrai", "Toutes"], 3,
      "Troyes, Lyon et Cambrai ont chacune leur andouillette typique."),

    # ============================ GÉNÉRATION 40 ANS (30) ============================
    Q("q40_1", "culture-40-ans", "Quel dessin animé met en scène un robot géant et son pilote Actarus ?",
      ["Albator", "Goldorak", "Capitaine Flam", "Cobra"], 1,
      "Goldorak, diffusé en 1978 sur Antenne 2."),
    Q("q40_2", "culture-40-ans", "Année où l'euro est devenu monnaie quotidienne en France ?",
      ["1999", "2000", "2002", "2004"], 2,
      "Le 1ᵉʳ janvier 2002, pièces et billets en euros."),
    Q("q40_3", "culture-40-ans", "Quel groupe a marqué les 80-90 avec « L'Aventurier » ?",
      ["Indochine", "Téléphone", "Les Innocents", "Cookie Dingler"], 0,
      "Indochine, formé en 1981."),
    Q("q40_4", "culture-40-ans", "Quel téléphone Nokia est devenu un phénomène en 2000 ?",
      ["Nokia 3210", "Nokia 3310", "Nokia 8210", "Nokia 6610"], 1,
      "Nokia 3310, plus de 126 millions d'exemplaires vendus."),
    Q("q40_5", "culture-40-ans", "Quel film de 1995 a révélé Mathieu Kassovitz comme réalisateur ?",
      ["La Haine", "Métisse", "Les Rivières pourpres", "Assassin(s)"], 0,
      "« La Haine » (1995), avec Vincent Cassel."),
    Q("q40_6", "culture-40-ans", "Qui a remporté la Coupe du monde de football en 1998 ?",
      ["Le Brésil", "La France", "L'Italie", "L'Allemagne"], 1,
      "La France 3-0 contre le Brésil au Stade de France."),
    Q("q40_7", "culture-40-ans", "Qui a écrit « Harry Potter » ?",
      ["Stephen King", "J.K. Rowling", "Roald Dahl", "Philip Pullman"], 1,
      "J.K. Rowling, premier tome publié en 1997."),
    Q("q40_8", "culture-40-ans", "Qui chante « Les Démons de minuit » en 1986 ?",
      ["Émile et Images", "Niagara", "Indochine", "Téléphone"], 0,
      "Émile et Images, tube de l'été 1986."),
    Q("q40_9", "culture-40-ans", "Année de la démocratisation d'Internet en France ?",
      ["1990", "1995", "2000", "2005"], 1,
      "1995 : arrivée des premiers FAI grand public."),
    Q("q40_10", "culture-40-ans", "Quel jeu Nintendo 64 est sorti en 1996 ?",
      ["Super Mario 64", "Zelda Ocarina of Time", "Mario Kart 64", "Donkey Kong 64"], 0,
      "« Super Mario 64 » a révolutionné la plateforme 3D."),
    Q("q40_11", "culture-40-ans", "Quel Disney a marqué 1994 en Afrique ?",
      ["Le Roi Lion", "Aladdin", "Pocahontas", "Tarzan"], 0,
      "« Le Roi Lion », l'un des plus grands succès d'animation."),
    Q("q40_12", "culture-40-ans", "Qui a chanté à l'aube de l'an 2000 au Stade de France ?",
      ["Johnny Hallyday", "Patrick Bruel", "Michel Sardou", "Pascal Obispo"], 0,
      "Johnny Hallyday, concert mémorable du 31 décembre 1999."),
    Q("q40_13", "culture-40-ans", "Quel film de Luc Besson révèle Natalie Portman en 1994 ?",
      ["Léon", "Le Cinquième Élément", "Nikita", "Subway"], 0,
      "« Léon » avec Jean Reno, Portman avait 12 ans."),
    Q("q40_14", "culture-40-ans", "Combien de mandats Mitterrand a-t-il effectués ?",
      ["1", "2", "3", "Aucun complet"], 1,
      "Deux mandats (1981-1995). Chirac lui succède."),
    Q("q40_15", "culture-40-ans", "Quel jeu de société des années 80 teste la culture générale ?",
      ["Monopoly", "Trivial Pursuit", "Cluedo", "Risk"], 1,
      "Le Trivial Pursuit, créé en 1981."),
    Q("q40_16", "culture-40-ans", "Quelle série suivait trois amies à Saint-Tropez ?",
      ["Hélène et les Garçons", "Premiers Baisers", "Sous le Soleil", "Salut les Musclés"], 2,
      "« Sous le Soleil » (1996-2008) sur TF1."),
    Q("q40_17", "culture-40-ans", "Quel iPhone a lancé la révolution smartphone ?",
      ["iPod Touch", "iPhone (1ᵉʳ)", "iPad", "MacBook"], 1,
      "L'iPhone, présenté par Steve Jobs le 9 janvier 2007."),
    Q("q40_18", "culture-40-ans", "Quel boys band français a percé avec « Be My Lady » ?",
      ["Alliage", "G-Squad", "2 Be 3", "Worlds Apart"], 0,
      "Alliage, succès fulgurant en 1996."),
    Q("q40_19", "culture-40-ans", "Quel jeu TF1 lance Foucault en 2000 ?",
      ["Le Juste Prix", "Qui veut gagner des millions ?", "La Roue de la fortune", "Tournez Manège"], 1,
      "« Qui veut gagner des millions ? », record d'audience."),
    Q("q40_20", "culture-40-ans", "Quel film de Dany Boon a fait 20M d'entrées en 2008 ?",
      ["Bienvenue chez les Ch'tis", "Rien à déclarer", "La Maison du Bonheur", "Eyjafjallajökull"], 0,
      "« Bienvenue chez les Ch'tis », record absolu en France."),
    Q("q40_21", "culture-40-ans", "Quel groupe pop des 80s chante « Voyage voyage » ?",
      ["Desireless", "Niagara", "Mylène Farmer", "Lio"], 0,
      "Desireless, tube planétaire de 1986."),
    Q("q40_22", "culture-40-ans", "Quel jeu vidéo a popularisé le « MMORPG » dans les 2000s ?",
      ["World of Warcraft", "EverQuest", "Final Fantasy", "Diablo"], 0,
      "World of Warcraft, lancé en 2004."),
    Q("q40_23", "culture-40-ans", "Quel film de Pixar a inauguré l'ère du tout-numérique en 1995 ?",
      ["Toy Story", "Le Monde de Nemo", "1001 Pattes", "Monstres et Cie"], 0,
      "« Toy Story », premier long-métrage entièrement en 3D."),
    Q("q40_24", "culture-40-ans", "Quel rappeur français a popularisé le rap avec « Tonton du bled » ?",
      ["MC Solaar", "113", "IAM", "NTM"], 1,
      "Le groupe 113, « Tonton du bled » (1999)."),
    Q("q40_25", "culture-40-ans", "Quel jeu de console a démocratisé la course de karting ?",
      ["Mario Kart", "Crash Team Racing", "Diddy Kong Racing", "Ridge Racer"], 0,
      "Mario Kart (Super Nintendo en 1992, puis N64 en 1996)."),
    Q("q40_26", "culture-40-ans", "Quel chanteur français a chanté « Sentinelle » et « Quelque chose de Tennessee » ?",
      ["Johnny Hallyday", "Étienne Daho", "Patrick Bruel", "Michel Berger"], 0,
      "Johnny Hallyday, « Quelque chose de Tennessee » (1985)."),
    Q("q40_27", "culture-40-ans", "Quel film Marvel a lancé le MCU en 2008 ?",
      ["Iron Man", "Thor", "Captain America", "Hulk"], 0,
      "« Iron Man » avec Robert Downey Jr., début du Marvel Cinematic Universe."),
    Q("q40_28", "culture-40-ans", "Quel président français a été élu en 1995 ?",
      ["Jospin", "Chirac", "Balladur", "Le Pen"], 1,
      "Jacques Chirac bat Lionel Jospin au second tour."),
    Q("q40_29", "culture-40-ans", "Quel jeu vidéo Pokémon est sorti sur Game Boy en France en 1999 ?",
      ["Rouge et Bleu", "Or et Argent", "Cristal", "Rubis et Saphir"], 0,
      "Pokémon Rouge et Bleu, lancement européen en 1999."),
    Q("q40_30", "culture-40-ans", "Quel chanteur français a interprété « Aux enfants de la balle » ?",
      ["Pascal Obispo", "Garou", "Patrick Bruel", "Florent Pagny"], 2,
      "Patrick Bruel, en duo avec Francis Cabrel sur scène."),

    # ============================ GÉNÉRATION 70 ANS (30) ============================
    Q("q70_1", "culture-70-ans", "Année du premier pas sur la Lune ?",
      ["1965", "1969", "1972", "1975"], 1,
      "Neil Armstrong, 21 juillet 1969."),
    Q("q70_2", "culture-70-ans", "Quel président US a été assassiné à Dallas en 1963 ?",
      ["Lyndon Johnson", "John F. Kennedy", "Richard Nixon", "Eisenhower"], 1,
      "JFK, le 22 novembre 1963."),
    Q("q70_3", "culture-70-ans", "Quel mur a divisé Berlin de 1961 à 1989 ?",
      ["Mur de Berlin", "Mur de Paris", "Mur d'Athènes", "Mur de Vienne"], 0,
      "Le Mur de Berlin, séparation Est/Ouest, chute le 9 novembre 1989."),
    Q("q70_4", "culture-70-ans", "Quel groupe britannique a marqué les 60s avec « Yesterday » ?",
      ["The Rolling Stones", "The Beatles", "Pink Floyd", "The Who"], 1,
      "The Beatles (1965), composée par Paul McCartney."),
    Q("q70_5", "culture-70-ans", "Qui dirigeait l'URSS lors de la crise des missiles de 1962 ?",
      ["Staline", "Khrouchtchev", "Brejnev", "Gorbatchev"], 1,
      "Nikita Khrouchtchev a négocié avec Kennedy."),
    Q("q70_6", "culture-70-ans", "Découverte majeure de 1953 par Watson et Crick ?",
      ["La pénicilline", "La structure de l'ADN", "La radioactivité", "Le vaccin polio"], 1,
      "La double hélice de l'ADN, révolution de la biologie."),
    Q("q70_7", "culture-70-ans", "Quel pays accueille les JO d'été en 1968 ?",
      ["Le Japon", "Le Mexique", "L'Allemagne", "Le Canada"], 1,
      "Mexico 1968 (poing levé des athlètes afro-américains)."),
    Q("q70_8", "culture-70-ans", "Mouvement pacifiste des 60s aux USA ?",
      ["Le hippie", "Le punk", "Le grunge", "Le rock"], 0,
      "Le mouvement hippie, opposé à la guerre du Vietnam."),
    Q("q70_9", "culture-70-ans", "Auteur de « Le Deuxième Sexe » (1949) ?",
      ["Simone de Beauvoir", "Marguerite Duras", "Colette", "Simone Veil"], 0,
      "Simone de Beauvoir, œuvre fondatrice du féminisme."),
    Q("q70_10", "culture-70-ans", "Quel avion supersonique a relié Paris-NY en 1976 ?",
      ["Boeing 747", "Concorde", "Airbus A300", "Tupolev Tu-144"], 1,
      "Le Concorde, coopération franco-britannique, vol jusqu'en 2003."),
    Q("q70_11", "culture-70-ans", "Qui a gagné 5 Tours de France entre 1969 et 1974 ?",
      ["Bernard Hinault", "Eddy Merckx", "Jacques Anquetil", "Miguel Indurain"], 1,
      "Eddy Merckx, « le Cannibale »."),
    Q("q70_12", "culture-70-ans", "Auteur de « L'Être et le Néant » (1943) ?",
      ["Albert Camus", "Jean-Paul Sartre", "Maurice Merleau-Ponty", "Raymond Aron"], 1,
      "Jean-Paul Sartre, figure de l'existentialisme."),
    Q("q70_13", "culture-70-ans", "Invention de 1947 qui révolutionne l'électronique ?",
      ["Le transistor", "Le tube cathodique", "Le micro-processeur", "Le laser"], 0,
      "Le transistor (Bell Labs, 1947), miniaturisation."),
    Q("q70_14", "culture-70-ans", "Quel président français abolit la peine de mort ?",
      ["Giscard", "Mitterrand", "Pompidou", "Chirac"], 1,
      "Mitterrand, loi du 9 octobre 1981 (Robert Badinter)."),
    Q("q70_15", "culture-70-ans", "Surnom de Cassius Clay alias Muhammad Ali ?",
      ["The Brown Bomber", "The Greatest", "The Big Slugger", "Sugar Ray"], 1,
      "« The Greatest », triple champion du monde poids lourds."),
    Q("q70_16", "culture-70-ans", "Quelle ville accueille l'Exposition universelle de 1937 ?",
      ["Lyon", "Marseille", "Paris", "Lille"], 2,
      "Paris : confrontation des pavillons soviétique et nazi."),
    Q("q70_17", "culture-70-ans", "Qui a peint « Guernica » en 1937 ?",
      ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Marc Chagall"], 1,
      "Pablo Picasso, en réaction au bombardement de Guernica."),
    Q("q70_18", "culture-70-ans", "Quel président US a démissionné après le Watergate ?",
      ["Lyndon Johnson", "Richard Nixon", "Gerald Ford", "Jimmy Carter"], 1,
      "Richard Nixon, le 9 août 1974."),
    Q("q70_19", "culture-70-ans", "Qui a lancé la Révolution culturelle en Chine en 1966 ?",
      ["Sun Yat-sen", "Mao Zedong", "Deng Xiaoping", "Tchang Kaï-chek"], 1,
      "Mao Zedong, mouvement qui durera 10 ans."),
    Q("q70_20", "culture-70-ans", "Année du discours de De Gaulle à Phnom Penh ?",
      ["1962", "1966", "1968", "1970"], 1,
      "1ᵉʳ septembre 1966 : il condamne l'intervention américaine au Vietnam."),
    Q("q70_21", "culture-70-ans", "Premier homme dans l'espace en 1961 ?",
      ["Iouri Gagarine", "Alan Shepard", "Valentina Terechkova", "John Glenn"], 0,
      "Iouri Gagarine, 12 avril 1961, vol Vostok 1."),
    Q("q70_22", "culture-70-ans", "Quel groupe a chanté « (I Can't Get No) Satisfaction » ?",
      ["Beatles", "Rolling Stones", "Who", "Kinks"], 1,
      "The Rolling Stones, 1965, hymne du rock."),
    Q("q70_23", "culture-70-ans", "Quel chancelier a marqué l'Allemagne d'après-guerre ?",
      ["Adenauer", "Brandt", "Schmidt", "Tous"], 3,
      "Tous : Adenauer (50s), Brandt (60-70s), Schmidt (70s)."),
    Q("q70_24", "culture-70-ans", "Où ont eu lieu les JO de 1972 marqués par un attentat ?",
      ["Mexico", "Munich", "Montréal", "Moscou"], 1,
      "Munich 1972 : massacre des athlètes israéliens par Septembre noir."),
    Q("q70_25", "culture-70-ans", "Découvreur du vaccin contre la polio ?",
      ["Pasteur", "Salk", "Fleming", "Sabin"], 1,
      "Jonas Salk en 1955 (Sabin a développé le vaccin oral en 1961)."),
    Q("q70_26", "culture-70-ans", "Auteur de « 1984 » publié en 1949 ?",
      ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Philip K. Dick"], 1,
      "George Orwell, dystopie totalitaire devenue classique."),
    Q("q70_27", "culture-70-ans", "Quelle catastrophe ferroviaire en France a marqué 1968 ?",
      ["Le crash du Concorde", "Aucune majeure", "Le déraillement de Dijon", "L'incendie de Vierzy"], 3,
      "Tunnel de Vierzy, 16 juin 1972 (108 morts)."),
    Q("q70_28", "culture-70-ans", "Quel président américain a engagé les USA au Vietnam ?",
      ["Truman", "Eisenhower", "Kennedy", "Tous"], 3,
      "Truman, Eisenhower puis Kennedy ont successivement engagé les États-Unis."),
    Q("q70_29", "culture-70-ans", "Quel scientifique a établi la relativité générale en 1915 ?",
      ["Newton", "Einstein", "Bohr", "Planck"], 1,
      "Albert Einstein, qui obtient le Nobel en 1921."),
    Q("q70_30", "culture-70-ans", "Année de Woodstock ?",
      ["1967", "1968", "1969", "1970"], 2,
      "15-18 août 1969, à Bethel (USA), 400 000 spectateurs."),
]
